--this is generated login file 
CREATE OR REPLACE ROLE ROLE_SUPERKOUC; 
GRANT ROLE ROLE_SUPERKOUC TO USER sfadmin; 
CREATE OR REPLACE ROLE ROLE_KOUC; 
GRANT USAGE ON DATABASE COURSES TO ROLE ROLE_KOUC; 
/* * * * * * * *  * * * * **********************************/ 
--VYTVORENI KOUCUCREATE OR REPLACE USER KOUC_KOUC PASSWORD = 'SpANEKSeNePRECENUJE', EMAIL = 'pavel@chocholous.net', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.PUBLIC', DEFAULT_ROLE = 'ROLE_KOUC'; 
GRANT ROLE ROLE_KOUC TO USER KOUC_KOUC; 

--USER LOGIN, SCHEMA, ROLE 
-- VYTVORENI SCHEMAT A ROLI NODE CZECHITA; 
CREATE OR REPLACE ROLE ROLE_CZECHITA; 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KOUC; 
CREATE OR REPLACE SCHEMA SCH_CZECHITA; 
CREATE OR REPLACE SCHEMA SCH_CZECHITA_HRISTE; 
create or replace TABLE SCH_CZECHITA.TEROR_DPJ22 (   EVENTID NUMBER(38,0),   IYEAR NUMBER(38,0),   IMONTH NUMBER(38,0),   IDAY NUMBER(38,0),   APPROXDATE VARCHAR(16777216),   EXTENDED NUMBER(38,0),   RESOLUTION NUMBER(38,0),   COUNTRY NUMBER(38,0),   COUNTRY_TXT VARCHAR(16777216),   REGION NUMBER(38,0),   REGION_TXT VARCHAR(16777216),   PROVSTATE VARCHAR(16777216),   CITY VARCHAR(16777216),   LATITUDE NUMBER(12,8),   LONGITUDE NUMBER(12,8),   SPECIFICITY NUMBER(38,0),   VICINITY NUMBER(38,0),   LOCATION VARCHAR(16777216),   SUMMARY VARCHAR(16777216),   CRIT1 NUMBER(38,0),   CRIT2 NUMBER(38,0),   CRIT3 NUMBER(38,0),   DOUBTTERR NUMBER(38,0),   ALTERNATIVE NUMBER(38,0),   ALTERNATIVE_TXT VARCHAR(16777216),   MULTIPLE NUMBER(38,0),   SUCCESS NUMBER(38,0),   SUICIDE NUMBER(38,0),   ATTACKTYPE1 NUMBER(38,0),   ATTACKTYPE1_TXT VARCHAR(16777216),   ATTACKTYPE2 NUMBER(38,0),   ATTACKTYPE2_TXT VARCHAR(16777216),   ATTACKTYPE3 NUMBER(38,0),   ATTACKTYPE3_TXT VARCHAR(16777216),   TARGTYPE1 NUMBER(38,0),   TARGTYPE1_TXT VARCHAR(16777216),   TARGSUBTYPE1 NUMBER(38,0),   TARGSUBTYPE1_TXT VARCHAR(16777216),   CORP1 VARCHAR(16777216),   TARGET1 VARCHAR(16777216),   NATLTY1 NUMBER(38,0),   NATLTY1_TXT VARCHAR(16777216),   TARGTYPE2 NUMBER(38,0),   TARGTYPE2_TXT VARCHAR(16777216),   TARGSUBTYPE2 NUMBER(38,0),   TARGSUBTYPE2_TXT VARCHAR(16777216),   CORP2 VARCHAR(16777216),   TARGET2 VARCHAR(16777216),   NATLTY2 NUMBER(38,0),   NATLTY2_TXT VARCHAR(16777216),   TARGTYPE3 NUMBER(38,0),   TARGTYPE3_TXT VARCHAR(16777216),   TARGSUBTYPE3 NUMBER(38,0),   TARGSUBTYPE3_TXT VARCHAR(16777216),   CORP3 VARCHAR(16777216),   TARGET3 VARCHAR(16777216),   NATLTY3 NUMBER(38,0),   NATLTY3_TXT VARCHAR(16777216),   GNAME VARCHAR(16777216),   GSUBNAME VARCHAR(16777216),   GNAME2 VARCHAR(16777216),   GSUBNAME2 VARCHAR(16777216),   GNAME3 VARCHAR(16777216),   GSUBNAME3 VARCHAR(16777216),   MOTIVE VARCHAR(16777216),   GUNCERTAIN1 NUMBER(38,0),   GUNCERTAIN2 NUMBER(38,0),   GUNCERTAIN3 NUMBER(38,0),   INDIVIDUAL NUMBER(38,0),   NPERPS NUMBER(38,0),   NPERPCAP NUMBER(38,0),   CLAIMED NUMBER(38,0),   CLAIMMODE NUMBER(38,0),   CLAIMMODE_TXT VARCHAR(16777216),   CLAIM2 VARCHAR(16777216),   CLAIMMODE2 VARCHAR(16777216),   CLAIMMODE2_TXT VARCHAR(16777216),   CLAIM3 VARCHAR(16777216),   CLAIMMODE3 VARCHAR(16777216),   CLAIMMODE3_TXT VARCHAR(16777216),   COMPCLAIM VARCHAR(16777216),   WEAPTYPE1 NUMBER(38,0),   WEAPTYPE1_TXT VARCHAR(16777216),   WEAPSUBTYPE1 NUMBER(38,0),   WEAPSUBTYPE1_TXT VARCHAR(16777216),   WEAPTYPE2 NUMBER(38,0),   WEAPTYPE2_TXT VARCHAR(16777216),   WEAPSUBTYPE2 NUMBER(38,0),   WEAPSUBTYPE2_TXT VARCHAR(16777216),   WEAPTYPE3 NUMBER(38,0),   WEAPTYPE3_TXT VARCHAR(16777216),   WEAPSUBTYPE3 NUMBER(38,0),   WEAPSUBTYPE3_TXT VARCHAR(16777216),   WEAPTYPE4 NUMBER(38,0),   WEAPTYPE4_TXT VARCHAR(16777216),   WEAPSUBTYPE4 NUMBER(38,0),   WEAPSUBTYPE4_TXT VARCHAR(16777216),   WEAPDETAIL VARCHAR(16777216),   NKILL NUMBER(38,0),   NKILLUS NUMBER(38,0),   NKILLTER NUMBER(38,0),   NWOUND NUMBER(38,0),   NWOUNDUS NUMBER(38,0),   NWOUNDTE NUMBER(38,0),   PROPERTY NUMBER(38,0),   PROPEXTENT NUMBER(38,0),   PROPEXTENT_TXT VARCHAR(16777216),   PROPVALUE NUMBER(38,0),   PROPCOMMENT VARCHAR(16777216),   ISHOSTKID NUMBER(38,0),   NHOSTKID NUMBER(38,0),   NHOSTKIDUS NUMBER(38,0),   NHOURS NUMBER(38,0),   NDAYS NUMBER(38,0),   DIVERT VARCHAR(16777216),   KIDHIJCOUNTRY VARCHAR(16777216),   RANSOM NUMBER(38,0),   RANSOMAMT NUMBER(16,4),   RANSOMAMTUS NUMBER(16,4),   RANSOMPAID NUMBER(16,4),   RANSOMPAIDUS NUMBER(16,4),   RANSOMNOTE VARCHAR(16777216),   HOSTKIDOUTCOME NUMBER(38,0),   HOSTKIDOUTCOME_TXT VARCHAR(16777216),   NRELEASED NUMBER(38,0),   ADDNOTES VARCHAR(16777216),   SCITE1 VARCHAR(16777216),   SCITE2 VARCHAR(16777216),   SCITE3 VARCHAR(16777216),   DBSOURCE VARCHAR(16777216),   INT_LOG NUMBER(38,0),   INT_IDEO NUMBER(38,0),   INT_MISC NUMBER(38,0),   INT_ANY NUMBER(38,0),   RELATED VARCHAR(16777216)  ); 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_TEST24;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_TEST24;
CREATE OR REPLACE USER CZECHITA_TEST24 PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'pavel@chocholous.net', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_TEST24'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_SUSTROVAM;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_SUSTROVAM;
CREATE OR REPLACE USER CZECHITA_SUSTROVAM PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'vase_marie@volny.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_SUSTROVAM'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_AMBRUSOVAT;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_AMBRUSOVAT;
CREATE OR REPLACE USER CZECHITA_AMBRUSOVAT PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 't.ambrusova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_AMBRUSOVAT'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_ANTOSOVAD;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_ANTOSOVAD;
CREATE OR REPLACE USER CZECHITA_ANTOSOVAD PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'd.antosova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_ANTOSOVAD'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_DVORACKOVAV;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_DVORACKOVAV;
CREATE OR REPLACE USER CZECHITA_DVORACKOVAV PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'vendula.dvorackova.vd@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_DVORACKOVAV'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_ERZINAM;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_ERZINAM;
CREATE OR REPLACE USER CZECHITA_ERZINAM PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'erzinamr@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_ERZINAM'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_HAJKOVAK;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_HAJKOVAK;
CREATE OR REPLACE USER CZECHITA_HAJKOVAK PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'karen.hajkova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_HAJKOVAK'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KARMINOVAE;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KARMINOVAE;
CREATE OR REPLACE USER CZECHITA_KARMINOVAE PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'karminova.edita@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KARMINOVAE'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KARTAKOVAT;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KARTAKOVAT;
CREATE OR REPLACE USER CZECHITA_KARTAKOVAT PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'kartakovat@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KARTAKOVAT'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KOCANDOVAA;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KOCANDOVAA;
CREATE OR REPLACE USER CZECHITA_KOCANDOVAA PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'alena.rezacova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KOCANDOVAA'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KOLARIKOVAL;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KOLARIKOVAL;
CREATE OR REPLACE USER CZECHITA_KOLARIKOVAL PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'lucia.j.kolarikova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KOLARIKOVAL'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KOLIASOVAN;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KOLIASOVAN;
CREATE OR REPLACE USER CZECHITA_KOLIASOVAN PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'nelakoliasova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KOLIASOVAN'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KOUDELKOVAL;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KOUDELKOVAL;
CREATE OR REPLACE USER CZECHITA_KOUDELKOVAL PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'lenkakoudelkova2@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KOUDELKOVAL'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KRALICKOVAZ;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KRALICKOVAZ;
CREATE OR REPLACE USER CZECHITA_KRALICKOVAZ PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'zuzkaalx@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KRALICKOVAZ'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KRIZKOVAM;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KRIZKOVAM;
CREATE OR REPLACE USER CZECHITA_KRIZKOVAM PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'maegda83@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KRIZKOVAM'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KUMPEROVAK;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KUMPEROVAK;
CREATE OR REPLACE USER CZECHITA_KUMPEROVAK PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'katerinakumperova010@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KUMPEROVAK'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KUSHNIRV;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KUSHNIRV;
CREATE OR REPLACE USER CZECHITA_KUSHNIRV PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'viktorkaua777@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KUSHNIRV'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_LUKESOVAP;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_LUKESOVAP;
CREATE OR REPLACE USER CZECHITA_LUKESOVAP PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'lukesova.pavlina@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_LUKESOVAP'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_MAKOVSKAR;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_MAKOVSKAR;
CREATE OR REPLACE USER CZECHITA_MAKOVSKAR PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'romana.makovska@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_MAKOVSKAR'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_MARJENKOVAN;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_MARJENKOVAN;
CREATE OR REPLACE USER CZECHITA_MARJENKOVAN PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'vargova.nikolka@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_MARJENKOVAN'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_MAZANKOVAK;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_MAZANKOVAK;
CREATE OR REPLACE USER CZECHITA_MAZANKOVAK PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'mazankok1998@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_MAZANKOVAK'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_MIHALIKOVAS;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_MIHALIKOVAS;
CREATE OR REPLACE USER CZECHITA_MIHALIKOVAS PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'silvamihalik@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_MIHALIKOVAS'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_MOZHAROVAA;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_MOZHAROVAA;
CREATE OR REPLACE USER CZECHITA_MOZHAROVAA PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'mozharova.nas@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_MOZHAROVAA'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_NGUYENT;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_NGUYENT;
CREATE OR REPLACE USER CZECHITA_NGUYENT PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'trami.nguyen392@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_NGUYENT'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_PAKOSTOVAI;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_PAKOSTOVAI;
CREATE OR REPLACE USER CZECHITA_PAKOSTOVAI PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'Ifca.Gabi@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_PAKOSTOVAI'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_PAVELKOVAA;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_PAVELKOVAA;
CREATE OR REPLACE USER CZECHITA_PAVELKOVAA PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'ann.pavelkova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_PAVELKOVAA'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_PAZDZIOROVAI;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_PAZDZIOROVAI;
CREATE OR REPLACE USER CZECHITA_PAZDZIOROVAI PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'ivana.pazdziorova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_PAZDZIOROVAI'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_PRIBILOVAZ;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_PRIBILOVAZ;
CREATE OR REPLACE USER CZECHITA_PRIBILOVAZ PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'zuzana.pribilova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_PRIBILOVAZ'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_RUZICKOVAH;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_RUZICKOVAH;
CREATE OR REPLACE USER CZECHITA_RUZICKOVAH PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'hana.forstova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_RUZICKOVAH'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_RUZICKOVAS;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_RUZICKOVAS;
CREATE OR REPLACE USER CZECHITA_RUZICKOVAS PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'stepa.ruzickova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_RUZICKOVAS'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_SIMERSKAM;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_SIMERSKAM;
CREATE OR REPLACE USER CZECHITA_SIMERSKAM PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'msimerska@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_SIMERSKAM'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_SMONDRKZ;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_SMONDRKZ;
CREATE OR REPLACE USER CZECHITA_SMONDRKZ PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'zuzana.smondrk@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_SMONDRKZ'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_SUSKOVAM;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_SUSKOVAM;
CREATE OR REPLACE USER CZECHITA_SUSKOVAM PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'martina.suskova93@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_SUSKOVAM'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_VAVROVAL;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_VAVROVAL;
CREATE OR REPLACE USER CZECHITA_VAVROVAL PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'vavrlenk@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_VAVROVAL'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_VRBASOVAK;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_VRBASOVAK;
CREATE OR REPLACE USER CZECHITA_VRBASOVAK PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'vrbasovak@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_VRBASOVAK'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_ZIKMUNDOVAL;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_ZIKMUNDOVAL;
CREATE OR REPLACE USER CZECHITA_ZIKMUNDOVAL PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'lazzikmundova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_ZIKMUNDOVAL'; 
-- GRANTNUTI PRAV KOUCUM PRO NODE CZECHITA; 
GRANT ROLE ROLE_CZECHITA_KOUC TO ROLE ROLE_SUPERKOUC; 
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KOUC; 
 /*UNCOMMENT AT WILL 
-- ROLES FOR CZECHITA
GRANT ROLE ROLE_CZECHITA_KOUC TO USER KOUC_KOUC; 
UNCOMMENT AT WILL */ 

--GRANT SELECT ON SCHEMAS TO ROLES 
GRANT USAGE ON DATABASE COURSES TO ROLE ROLE_CZECHITA; 
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_CZECHITA; 
GRANT USAGE ON SCHEMA SCH_CZECHITA TO ROLE ROLE_CZECHITA; 
GRANT SELECT ON ALL TABLES IN SCHEMA SCH_CZECHITA TO ROLE ROLE_CZECHITA; 
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCH_CZECHITA TO ROLE ROLE_CZECHITA; 
GRANT USAGE ON SCHEMA SCH_CZECHITA_HRISTE TO ROLE ROLE_CZECHITA; 
GRANT SELECT ON ALL TABLES IN SCHEMA SCH_CZECHITA_HRISTE TO ROLE ROLE_CZECHITA; 
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_HRISTE TO ROLE ROLE_CZECHITA; 
GRANT ALL ON SCHEMA SCH_CZECHITA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA TO ROLE ROLE_CZECHITA_KOUC; 
 
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_TEST24;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_SUSTROVAM;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_AMBRUSOVAT;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_ANTOSOVAD;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_DVORACKOVAV;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_ERZINAM;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_HAJKOVAK;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KARMINOVAE;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KARTAKOVAT;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KOCANDOVAA;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KOLARIKOVAL;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KOLIASOVAN;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KOUDELKOVAL;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KRALICKOVAZ;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KRIZKOVAM;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KUMPEROVAK;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KUSHNIRV;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_LUKESOVAP;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_MAKOVSKAR;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_MARJENKOVAN;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_MAZANKOVAK;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_MIHALIKOVAS;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_MOZHAROVAA;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_NGUYENT;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_PAKOSTOVAI;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_PAVELKOVAA;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_PAZDZIOROVAI;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_PRIBILOVAZ;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_RUZICKOVAH;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_RUZICKOVAS;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_SIMERSKAM;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_SMONDRKZ;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_SUSKOVAM;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_VAVROVAL;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_VRBASOVAK;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_ZIKMUNDOVAL;
GRANT ALL ON SCHEMA SCH_CZECHITA_TEST24 TO ROLE ROLE_CZECHITA_TEST24; 
GRANT ROLE ROLE_CZECHITA_TEST24 TO USER CZECHITA_TEST24; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_TEST24 TO ROLE ROLE_CZECHITA_TEST24; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_TEST24 TO ROLE ROLE_CZECHITA_TEST24; 
GRANT ALL ON SCHEMA SCH_CZECHITA_TEST24 TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_TEST24 TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_TEST24 TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SUSTROVAM TO ROLE ROLE_CZECHITA_SUSTROVAM; 
GRANT ROLE ROLE_CZECHITA_SUSTROVAM TO USER CZECHITA_SUSTROVAM; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SUSTROVAM TO ROLE ROLE_CZECHITA_SUSTROVAM; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SUSTROVAM TO ROLE ROLE_CZECHITA_SUSTROVAM; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SUSTROVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SUSTROVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SUSTROVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_AMBRUSOVAT TO ROLE ROLE_CZECHITA_AMBRUSOVAT; 
GRANT ROLE ROLE_CZECHITA_AMBRUSOVAT TO USER CZECHITA_AMBRUSOVAT; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_AMBRUSOVAT TO ROLE ROLE_CZECHITA_AMBRUSOVAT; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_AMBRUSOVAT TO ROLE ROLE_CZECHITA_AMBRUSOVAT; 
GRANT ALL ON SCHEMA SCH_CZECHITA_AMBRUSOVAT TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_AMBRUSOVAT TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_AMBRUSOVAT TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_ANTOSOVAD TO ROLE ROLE_CZECHITA_ANTOSOVAD; 
GRANT ROLE ROLE_CZECHITA_ANTOSOVAD TO USER CZECHITA_ANTOSOVAD; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_ANTOSOVAD TO ROLE ROLE_CZECHITA_ANTOSOVAD; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_ANTOSOVAD TO ROLE ROLE_CZECHITA_ANTOSOVAD; 
GRANT ALL ON SCHEMA SCH_CZECHITA_ANTOSOVAD TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_ANTOSOVAD TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_ANTOSOVAD TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_DVORACKOVAV TO ROLE ROLE_CZECHITA_DVORACKOVAV; 
GRANT ROLE ROLE_CZECHITA_DVORACKOVAV TO USER CZECHITA_DVORACKOVAV; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_DVORACKOVAV TO ROLE ROLE_CZECHITA_DVORACKOVAV; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_DVORACKOVAV TO ROLE ROLE_CZECHITA_DVORACKOVAV; 
GRANT ALL ON SCHEMA SCH_CZECHITA_DVORACKOVAV TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_DVORACKOVAV TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_DVORACKOVAV TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_ERZINAM TO ROLE ROLE_CZECHITA_ERZINAM; 
GRANT ROLE ROLE_CZECHITA_ERZINAM TO USER CZECHITA_ERZINAM; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_ERZINAM TO ROLE ROLE_CZECHITA_ERZINAM; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_ERZINAM TO ROLE ROLE_CZECHITA_ERZINAM; 
GRANT ALL ON SCHEMA SCH_CZECHITA_ERZINAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_ERZINAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_ERZINAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_HAJKOVAK TO ROLE ROLE_CZECHITA_HAJKOVAK; 
GRANT ROLE ROLE_CZECHITA_HAJKOVAK TO USER CZECHITA_HAJKOVAK; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_HAJKOVAK TO ROLE ROLE_CZECHITA_HAJKOVAK; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_HAJKOVAK TO ROLE ROLE_CZECHITA_HAJKOVAK; 
GRANT ALL ON SCHEMA SCH_CZECHITA_HAJKOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_HAJKOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_HAJKOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KARMINOVAE TO ROLE ROLE_CZECHITA_KARMINOVAE; 
GRANT ROLE ROLE_CZECHITA_KARMINOVAE TO USER CZECHITA_KARMINOVAE; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KARMINOVAE TO ROLE ROLE_CZECHITA_KARMINOVAE; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KARMINOVAE TO ROLE ROLE_CZECHITA_KARMINOVAE; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KARMINOVAE TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KARMINOVAE TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KARMINOVAE TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KARTAKOVAT TO ROLE ROLE_CZECHITA_KARTAKOVAT; 
GRANT ROLE ROLE_CZECHITA_KARTAKOVAT TO USER CZECHITA_KARTAKOVAT; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KARTAKOVAT TO ROLE ROLE_CZECHITA_KARTAKOVAT; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KARTAKOVAT TO ROLE ROLE_CZECHITA_KARTAKOVAT; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KARTAKOVAT TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KARTAKOVAT TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KARTAKOVAT TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KOCANDOVAA TO ROLE ROLE_CZECHITA_KOCANDOVAA; 
GRANT ROLE ROLE_CZECHITA_KOCANDOVAA TO USER CZECHITA_KOCANDOVAA; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KOCANDOVAA TO ROLE ROLE_CZECHITA_KOCANDOVAA; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KOCANDOVAA TO ROLE ROLE_CZECHITA_KOCANDOVAA; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KOCANDOVAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KOCANDOVAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KOCANDOVAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KOLARIKOVAL TO ROLE ROLE_CZECHITA_KOLARIKOVAL; 
GRANT ROLE ROLE_CZECHITA_KOLARIKOVAL TO USER CZECHITA_KOLARIKOVAL; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KOLARIKOVAL TO ROLE ROLE_CZECHITA_KOLARIKOVAL; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KOLARIKOVAL TO ROLE ROLE_CZECHITA_KOLARIKOVAL; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KOLARIKOVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KOLARIKOVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KOLARIKOVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KOLIASOVAN TO ROLE ROLE_CZECHITA_KOLIASOVAN; 
GRANT ROLE ROLE_CZECHITA_KOLIASOVAN TO USER CZECHITA_KOLIASOVAN; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KOLIASOVAN TO ROLE ROLE_CZECHITA_KOLIASOVAN; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KOLIASOVAN TO ROLE ROLE_CZECHITA_KOLIASOVAN; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KOLIASOVAN TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KOLIASOVAN TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KOLIASOVAN TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KOUDELKOVAL TO ROLE ROLE_CZECHITA_KOUDELKOVAL; 
GRANT ROLE ROLE_CZECHITA_KOUDELKOVAL TO USER CZECHITA_KOUDELKOVAL; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KOUDELKOVAL TO ROLE ROLE_CZECHITA_KOUDELKOVAL; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KOUDELKOVAL TO ROLE ROLE_CZECHITA_KOUDELKOVAL; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KOUDELKOVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KOUDELKOVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KOUDELKOVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KRALICKOVAZ TO ROLE ROLE_CZECHITA_KRALICKOVAZ; 
GRANT ROLE ROLE_CZECHITA_KRALICKOVAZ TO USER CZECHITA_KRALICKOVAZ; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KRALICKOVAZ TO ROLE ROLE_CZECHITA_KRALICKOVAZ; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KRALICKOVAZ TO ROLE ROLE_CZECHITA_KRALICKOVAZ; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KRALICKOVAZ TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KRALICKOVAZ TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KRALICKOVAZ TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KRIZKOVAM TO ROLE ROLE_CZECHITA_KRIZKOVAM; 
GRANT ROLE ROLE_CZECHITA_KRIZKOVAM TO USER CZECHITA_KRIZKOVAM; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KRIZKOVAM TO ROLE ROLE_CZECHITA_KRIZKOVAM; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KRIZKOVAM TO ROLE ROLE_CZECHITA_KRIZKOVAM; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KRIZKOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KRIZKOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KRIZKOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KUMPEROVAK TO ROLE ROLE_CZECHITA_KUMPEROVAK; 
GRANT ROLE ROLE_CZECHITA_KUMPEROVAK TO USER CZECHITA_KUMPEROVAK; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KUMPEROVAK TO ROLE ROLE_CZECHITA_KUMPEROVAK; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KUMPEROVAK TO ROLE ROLE_CZECHITA_KUMPEROVAK; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KUMPEROVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KUMPEROVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KUMPEROVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KUSHNIRV TO ROLE ROLE_CZECHITA_KUSHNIRV; 
GRANT ROLE ROLE_CZECHITA_KUSHNIRV TO USER CZECHITA_KUSHNIRV; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KUSHNIRV TO ROLE ROLE_CZECHITA_KUSHNIRV; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KUSHNIRV TO ROLE ROLE_CZECHITA_KUSHNIRV; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KUSHNIRV TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KUSHNIRV TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KUSHNIRV TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_LUKESOVAP TO ROLE ROLE_CZECHITA_LUKESOVAP; 
GRANT ROLE ROLE_CZECHITA_LUKESOVAP TO USER CZECHITA_LUKESOVAP; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_LUKESOVAP TO ROLE ROLE_CZECHITA_LUKESOVAP; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_LUKESOVAP TO ROLE ROLE_CZECHITA_LUKESOVAP; 
GRANT ALL ON SCHEMA SCH_CZECHITA_LUKESOVAP TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_LUKESOVAP TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_LUKESOVAP TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MAKOVSKAR TO ROLE ROLE_CZECHITA_MAKOVSKAR; 
GRANT ROLE ROLE_CZECHITA_MAKOVSKAR TO USER CZECHITA_MAKOVSKAR; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MAKOVSKAR TO ROLE ROLE_CZECHITA_MAKOVSKAR; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MAKOVSKAR TO ROLE ROLE_CZECHITA_MAKOVSKAR; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MAKOVSKAR TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MAKOVSKAR TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MAKOVSKAR TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MARJENKOVAN TO ROLE ROLE_CZECHITA_MARJENKOVAN; 
GRANT ROLE ROLE_CZECHITA_MARJENKOVAN TO USER CZECHITA_MARJENKOVAN; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MARJENKOVAN TO ROLE ROLE_CZECHITA_MARJENKOVAN; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MARJENKOVAN TO ROLE ROLE_CZECHITA_MARJENKOVAN; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MARJENKOVAN TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MARJENKOVAN TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MARJENKOVAN TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MAZANKOVAK TO ROLE ROLE_CZECHITA_MAZANKOVAK; 
GRANT ROLE ROLE_CZECHITA_MAZANKOVAK TO USER CZECHITA_MAZANKOVAK; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MAZANKOVAK TO ROLE ROLE_CZECHITA_MAZANKOVAK; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MAZANKOVAK TO ROLE ROLE_CZECHITA_MAZANKOVAK; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MAZANKOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MAZANKOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MAZANKOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MIHALIKOVAS TO ROLE ROLE_CZECHITA_MIHALIKOVAS; 
GRANT ROLE ROLE_CZECHITA_MIHALIKOVAS TO USER CZECHITA_MIHALIKOVAS; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MIHALIKOVAS TO ROLE ROLE_CZECHITA_MIHALIKOVAS; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MIHALIKOVAS TO ROLE ROLE_CZECHITA_MIHALIKOVAS; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MIHALIKOVAS TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MIHALIKOVAS TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MIHALIKOVAS TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MOZHAROVAA TO ROLE ROLE_CZECHITA_MOZHAROVAA; 
GRANT ROLE ROLE_CZECHITA_MOZHAROVAA TO USER CZECHITA_MOZHAROVAA; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MOZHAROVAA TO ROLE ROLE_CZECHITA_MOZHAROVAA; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MOZHAROVAA TO ROLE ROLE_CZECHITA_MOZHAROVAA; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MOZHAROVAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MOZHAROVAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MOZHAROVAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_NGUYENT TO ROLE ROLE_CZECHITA_NGUYENT; 
GRANT ROLE ROLE_CZECHITA_NGUYENT TO USER CZECHITA_NGUYENT; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_NGUYENT TO ROLE ROLE_CZECHITA_NGUYENT; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_NGUYENT TO ROLE ROLE_CZECHITA_NGUYENT; 
GRANT ALL ON SCHEMA SCH_CZECHITA_NGUYENT TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_NGUYENT TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_NGUYENT TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PAKOSTOVAI TO ROLE ROLE_CZECHITA_PAKOSTOVAI; 
GRANT ROLE ROLE_CZECHITA_PAKOSTOVAI TO USER CZECHITA_PAKOSTOVAI; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PAKOSTOVAI TO ROLE ROLE_CZECHITA_PAKOSTOVAI; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PAKOSTOVAI TO ROLE ROLE_CZECHITA_PAKOSTOVAI; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PAKOSTOVAI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PAKOSTOVAI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PAKOSTOVAI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PAVELKOVAA TO ROLE ROLE_CZECHITA_PAVELKOVAA; 
GRANT ROLE ROLE_CZECHITA_PAVELKOVAA TO USER CZECHITA_PAVELKOVAA; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PAVELKOVAA TO ROLE ROLE_CZECHITA_PAVELKOVAA; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PAVELKOVAA TO ROLE ROLE_CZECHITA_PAVELKOVAA; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PAVELKOVAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PAVELKOVAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PAVELKOVAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PAZDZIOROVAI TO ROLE ROLE_CZECHITA_PAZDZIOROVAI; 
GRANT ROLE ROLE_CZECHITA_PAZDZIOROVAI TO USER CZECHITA_PAZDZIOROVAI; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PAZDZIOROVAI TO ROLE ROLE_CZECHITA_PAZDZIOROVAI; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PAZDZIOROVAI TO ROLE ROLE_CZECHITA_PAZDZIOROVAI; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PAZDZIOROVAI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PAZDZIOROVAI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PAZDZIOROVAI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PRIBILOVAZ TO ROLE ROLE_CZECHITA_PRIBILOVAZ; 
GRANT ROLE ROLE_CZECHITA_PRIBILOVAZ TO USER CZECHITA_PRIBILOVAZ; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PRIBILOVAZ TO ROLE ROLE_CZECHITA_PRIBILOVAZ; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PRIBILOVAZ TO ROLE ROLE_CZECHITA_PRIBILOVAZ; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PRIBILOVAZ TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PRIBILOVAZ TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PRIBILOVAZ TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_RUZICKOVAH TO ROLE ROLE_CZECHITA_RUZICKOVAH; 
GRANT ROLE ROLE_CZECHITA_RUZICKOVAH TO USER CZECHITA_RUZICKOVAH; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_RUZICKOVAH TO ROLE ROLE_CZECHITA_RUZICKOVAH; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_RUZICKOVAH TO ROLE ROLE_CZECHITA_RUZICKOVAH; 
GRANT ALL ON SCHEMA SCH_CZECHITA_RUZICKOVAH TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_RUZICKOVAH TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_RUZICKOVAH TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_RUZICKOVAS TO ROLE ROLE_CZECHITA_RUZICKOVAS; 
GRANT ROLE ROLE_CZECHITA_RUZICKOVAS TO USER CZECHITA_RUZICKOVAS; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_RUZICKOVAS TO ROLE ROLE_CZECHITA_RUZICKOVAS; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_RUZICKOVAS TO ROLE ROLE_CZECHITA_RUZICKOVAS; 
GRANT ALL ON SCHEMA SCH_CZECHITA_RUZICKOVAS TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_RUZICKOVAS TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_RUZICKOVAS TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SIMERSKAM TO ROLE ROLE_CZECHITA_SIMERSKAM; 
GRANT ROLE ROLE_CZECHITA_SIMERSKAM TO USER CZECHITA_SIMERSKAM; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SIMERSKAM TO ROLE ROLE_CZECHITA_SIMERSKAM; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SIMERSKAM TO ROLE ROLE_CZECHITA_SIMERSKAM; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SIMERSKAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SIMERSKAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SIMERSKAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SMONDRKZ TO ROLE ROLE_CZECHITA_SMONDRKZ; 
GRANT ROLE ROLE_CZECHITA_SMONDRKZ TO USER CZECHITA_SMONDRKZ; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SMONDRKZ TO ROLE ROLE_CZECHITA_SMONDRKZ; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SMONDRKZ TO ROLE ROLE_CZECHITA_SMONDRKZ; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SMONDRKZ TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SMONDRKZ TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SMONDRKZ TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SUSKOVAM TO ROLE ROLE_CZECHITA_SUSKOVAM; 
GRANT ROLE ROLE_CZECHITA_SUSKOVAM TO USER CZECHITA_SUSKOVAM; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SUSKOVAM TO ROLE ROLE_CZECHITA_SUSKOVAM; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SUSKOVAM TO ROLE ROLE_CZECHITA_SUSKOVAM; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SUSKOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SUSKOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SUSKOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_VAVROVAL TO ROLE ROLE_CZECHITA_VAVROVAL; 
GRANT ROLE ROLE_CZECHITA_VAVROVAL TO USER CZECHITA_VAVROVAL; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_VAVROVAL TO ROLE ROLE_CZECHITA_VAVROVAL; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_VAVROVAL TO ROLE ROLE_CZECHITA_VAVROVAL; 
GRANT ALL ON SCHEMA SCH_CZECHITA_VAVROVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_VAVROVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_VAVROVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_VRBASOVAK TO ROLE ROLE_CZECHITA_VRBASOVAK; 
GRANT ROLE ROLE_CZECHITA_VRBASOVAK TO USER CZECHITA_VRBASOVAK; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_VRBASOVAK TO ROLE ROLE_CZECHITA_VRBASOVAK; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_VRBASOVAK TO ROLE ROLE_CZECHITA_VRBASOVAK; 
GRANT ALL ON SCHEMA SCH_CZECHITA_VRBASOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_VRBASOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_VRBASOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_ZIKMUNDOVAL TO ROLE ROLE_CZECHITA_ZIKMUNDOVAL; 
GRANT ROLE ROLE_CZECHITA_ZIKMUNDOVAL TO USER CZECHITA_ZIKMUNDOVAL; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_ZIKMUNDOVAL TO ROLE ROLE_CZECHITA_ZIKMUNDOVAL; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_ZIKMUNDOVAL TO ROLE ROLE_CZECHITA_ZIKMUNDOVAL; 
GRANT ALL ON SCHEMA SCH_CZECHITA_ZIKMUNDOVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_ZIKMUNDOVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_ZIKMUNDOVAL TO ROLE ROLE_CZECHITA_KOUC; 
