--this is generated login file 
CREATE OR REPLACE ROLE ROLE_SUPERKOUC; 
GRANT ROLE ROLE_SUPERKOUC TO USER sfadmin; 
CREATE OR REPLACE ROLE ROLE_KOUC; 
GRANT USAGE ON DATABASE COURSES TO ROLE ROLE_KOUC; 
/* * * * * * * *  * * * * **********************************/ 
--VYTVORENI KOUCUCREATE OR REPLACE USER KOUC_KOUC PASSWORD = 'SpANEKSeNePRECENUJE', EMAIL = 'pavel@chocholous.net', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.PUBLIC', DEFAULT_ROLE = 'ROLE_KOUC'; 
GRANT ROLE ROLE_KOUC TO USER KOUC_KOUC; 

--USER LOGIN, SCHEMA, ROLE 
-- VYTVORENI SCHEMAT A ROLI NODE UK; 
--CREATE OR REPLACE ROLE ROLE_UK; 
--CREATE OR REPLACE ROLE ROLE_UK_KOUC; 
--CREATE OR REPLACE SCHEMA SCH_UK; 
--CREATE OR REPLACE SCHEMA SCH_UK_HRISTE; 
--create or replace TABLE SCH_UK.TEROR_DPJ22 (   EVENTID NUMBER(38,0),   IYEAR NUMBER(38,0),   IMONTH NUMBER(38,0),   IDAY NUMBER(38,0),   APPROXDATE VARCHAR(16777216),   EXTENDED NUMBER(38,0),   RESOLUTION NUMBER(38,0),   COUNTRY NUMBER(38,0),   COUNTRY_TXT VARCHAR(16777216),   REGION NUMBER(38,0),   REGION_TXT VARCHAR(16777216),   PROVSTATE VARCHAR(16777216),   CITY VARCHAR(16777216),   LATITUDE NUMBER(12,8),   LONGITUDE NUMBER(12,8),   SPECIFICITY NUMBER(38,0),   VICINITY NUMBER(38,0),   LOCATION VARCHAR(16777216),   SUMMARY VARCHAR(16777216),   CRIT1 NUMBER(38,0),   CRIT2 NUMBER(38,0),   CRIT3 NUMBER(38,0),   DOUBTTERR NUMBER(38,0),   ALTERNATIVE NUMBER(38,0),   ALTERNATIVE_TXT VARCHAR(16777216),   MULTIPLE NUMBER(38,0),   SUCCESS NUMBER(38,0),   SUICIDE NUMBER(38,0),   ATTACKTYPE1 NUMBER(38,0),   ATTACKTYPE1_TXT VARCHAR(16777216),   ATTACKTYPE2 NUMBER(38,0),   ATTACKTYPE2_TXT VARCHAR(16777216),   ATTACKTYPE3 NUMBER(38,0),   ATTACKTYPE3_TXT VARCHAR(16777216),   TARGTYPE1 NUMBER(38,0),   TARGTYPE1_TXT VARCHAR(16777216),   TARGSUBTYPE1 NUMBER(38,0),   TARGSUBTYPE1_TXT VARCHAR(16777216),   CORP1 VARCHAR(16777216),   TARGET1 VARCHAR(16777216),   NATLTY1 NUMBER(38,0),   NATLTY1_TXT VARCHAR(16777216),   TARGTYPE2 NUMBER(38,0),   TARGTYPE2_TXT VARCHAR(16777216),   TARGSUBTYPE2 NUMBER(38,0),   TARGSUBTYPE2_TXT VARCHAR(16777216),   CORP2 VARCHAR(16777216),   TARGET2 VARCHAR(16777216),   NATLTY2 NUMBER(38,0),   NATLTY2_TXT VARCHAR(16777216),   TARGTYPE3 NUMBER(38,0),   TARGTYPE3_TXT VARCHAR(16777216),   TARGSUBTYPE3 NUMBER(38,0),   TARGSUBTYPE3_TXT VARCHAR(16777216),   CORP3 VARCHAR(16777216),   TARGET3 VARCHAR(16777216),   NATLTY3 NUMBER(38,0),   NATLTY3_TXT VARCHAR(16777216),   GNAME VARCHAR(16777216),   GSUBNAME VARCHAR(16777216),   GNAME2 VARCHAR(16777216),   GSUBNAME2 VARCHAR(16777216),   GNAME3 VARCHAR(16777216),   GSUBNAME3 VARCHAR(16777216),   MOTIVE VARCHAR(16777216),   GUNCERTAIN1 NUMBER(38,0),   GUNCERTAIN2 NUMBER(38,0),   GUNCERTAIN3 NUMBER(38,0),   INDIVIDUAL NUMBER(38,0),   NPERPS NUMBER(38,0),   NPERPCAP NUMBER(38,0),   CLAIMED NUMBER(38,0),   CLAIMMODE NUMBER(38,0),   CLAIMMODE_TXT VARCHAR(16777216),   CLAIM2 VARCHAR(16777216),   CLAIMMODE2 VARCHAR(16777216),   CLAIMMODE2_TXT VARCHAR(16777216),   CLAIM3 VARCHAR(16777216),   CLAIMMODE3 VARCHAR(16777216),   CLAIMMODE3_TXT VARCHAR(16777216),   COMPCLAIM VARCHAR(16777216),   WEAPTYPE1 NUMBER(38,0),   WEAPTYPE1_TXT VARCHAR(16777216),   WEAPSUBTYPE1 NUMBER(38,0),   WEAPSUBTYPE1_TXT VARCHAR(16777216),   WEAPTYPE2 NUMBER(38,0),   WEAPTYPE2_TXT VARCHAR(16777216),   WEAPSUBTYPE2 NUMBER(38,0),   WEAPSUBTYPE2_TXT VARCHAR(16777216),   WEAPTYPE3 NUMBER(38,0),   WEAPTYPE3_TXT VARCHAR(16777216),   WEAPSUBTYPE3 NUMBER(38,0),   WEAPSUBTYPE3_TXT VARCHAR(16777216),   WEAPTYPE4 NUMBER(38,0),   WEAPTYPE4_TXT VARCHAR(16777216),   WEAPSUBTYPE4 NUMBER(38,0),   WEAPSUBTYPE4_TXT VARCHAR(16777216),   WEAPDETAIL VARCHAR(16777216),   NKILL NUMBER(38,0),   NKILLUS NUMBER(38,0),   NKILLTER NUMBER(38,0),   NWOUND NUMBER(38,0),   NWOUNDUS NUMBER(38,0),   NWOUNDTE NUMBER(38,0),   PROPERTY NUMBER(38,0),   PROPEXTENT NUMBER(38,0),   PROPEXTENT_TXT VARCHAR(16777216),   PROPVALUE NUMBER(38,0),   PROPCOMMENT VARCHAR(16777216),   ISHOSTKID NUMBER(38,0),   NHOSTKID NUMBER(38,0),   NHOSTKIDUS NUMBER(38,0),   NHOURS NUMBER(38,0),   NDAYS NUMBER(38,0),   DIVERT VARCHAR(16777216),   KIDHIJCOUNTRY VARCHAR(16777216),   RANSOM NUMBER(38,0),   RANSOMAMT NUMBER(16,4),   RANSOMAMTUS NUMBER(16,4),   RANSOMPAID NUMBER(16,4),   RANSOMPAIDUS NUMBER(16,4),   RANSOMNOTE VARCHAR(16777216),   HOSTKIDOUTCOME NUMBER(38,0),   HOSTKIDOUTCOME_TXT VARCHAR(16777216),   NRELEASED NUMBER(38,0),   ADDNOTES VARCHAR(16777216),   SCITE1 VARCHAR(16777216),   SCITE2 VARCHAR(16777216),   SCITE3 VARCHAR(16777216),   DBSOURCE VARCHAR(16777216),   INT_LOG NUMBER(38,0),   INT_IDEO NUMBER(38,0),   INT_MISC NUMBER(38,0),   INT_ANY NUMBER(38,0),   RELATED VARCHAR(16777216)  ); 
 
CREATE OR REPLACE ROLE ROLE_UK_STRYKAV;
CREATE OR REPLACE SCHEMA SCH_UK_STRYKAV;
CREATE OR REPLACE USER UK_STRYKAV PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'strykav@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_STRYKAV'; 
 
CREATE OR REPLACE ROLE ROLE_UK_HORCIKJ;
CREATE OR REPLACE SCHEMA SCH_UK_HORCIKJ;
CREATE OR REPLACE USER UK_HORCIKJ PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'horcikj@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_HORCIKJ'; 
 
CREATE OR REPLACE ROLE ROLE_UK_KVASNICKOVAL;
CREATE OR REPLACE SCHEMA SCH_UK_KVASNICKOVAL;
CREATE OR REPLACE USER UK_KVASNICKOVAL PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'lucia.kvasnickova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_KVASNICKOVAL'; 
 
CREATE OR REPLACE ROLE ROLE_UK_MAIEROVAT;
CREATE OR REPLACE SCHEMA SCH_UK_MAIEROVAT;
CREATE OR REPLACE USER UK_MAIEROVAT PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'maierovatereza07@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_MAIEROVAT'; 
 
CREATE OR REPLACE ROLE ROLE_UK_MASICKOVAK;
CREATE OR REPLACE SCHEMA SCH_UK_MASICKOVAK;
CREATE OR REPLACE USER UK_MASICKOVAK PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'masickok@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_MASICKOVAK'; 
 
CREATE OR REPLACE ROLE ROLE_UK_SENOHRABKOVAE;
CREATE OR REPLACE SCHEMA SCH_UK_SENOHRABKOVAE;
CREATE OR REPLACE USER UK_SENOHRABKOVAE PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'eliskaseno@seznam.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_SENOHRABKOVAE'; 
 
CREATE OR REPLACE ROLE ROLE_UK_TRINHM;
CREATE OR REPLACE SCHEMA SCH_UK_TRINHM;
CREATE OR REPLACE USER UK_TRINHM PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'trinhm@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_TRINHM'; 
 
CREATE OR REPLACE ROLE ROLE_UK_VESELAP;
CREATE OR REPLACE SCHEMA SCH_UK_VESELAP;
CREATE OR REPLACE USER UK_VESELAP PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'paja.ves@email.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_VESELAP'; 
 
CREATE OR REPLACE ROLE ROLE_UK_VOKOUNOVAT;
CREATE OR REPLACE SCHEMA SCH_UK_VOKOUNOVAT;
CREATE OR REPLACE USER UK_VOKOUNOVAT PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'terezka.vokounova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_VOKOUNOVAT'; 
 
CREATE OR REPLACE ROLE ROLE_UK_VYSKOCOVAK;
CREATE OR REPLACE SCHEMA SCH_UK_VYSKOCOVAK;
CREATE OR REPLACE USER UK_VYSKOCOVAK PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'katka.vyskocova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_VYSKOCOVAK'; 
 
CREATE OR REPLACE ROLE ROLE_UK_ADAMEKJ;
CREATE OR REPLACE SCHEMA SCH_UK_ADAMEKJ;
CREATE OR REPLACE USER UK_ADAMEKJ PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'adamekjakub@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_ADAMEKJ'; 
 
CREATE OR REPLACE ROLE ROLE_UK_BARTOSV;
CREATE OR REPLACE SCHEMA SCH_UK_BARTOSV;
CREATE OR REPLACE USER UK_BARTOSV PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'vacbarto@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_BARTOSV'; 
 
CREATE OR REPLACE ROLE ROLE_UK_HRUSKOVAZ;
CREATE OR REPLACE SCHEMA SCH_UK_HRUSKOVAZ;
CREATE OR REPLACE USER UK_HRUSKOVAZ PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'hruskovzuzan@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_HRUSKOVAZ'; 
 
CREATE OR REPLACE ROLE ROLE_UK_JANDIKJ;
CREATE OR REPLACE SCHEMA SCH_UK_JANDIKJ;
CREATE OR REPLACE USER UK_JANDIKJ PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'jandikjaku@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_JANDIKJ'; 
 
CREATE OR REPLACE ROLE ROLE_UK_JINDROVAA;
CREATE OR REPLACE SCHEMA SCH_UK_JINDROVAA;
CREATE OR REPLACE USER UK_JINDROVAA PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'jindrovann@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_JINDROVAA'; 
 
CREATE OR REPLACE ROLE ROLE_UK_KISSOVAT;
CREATE OR REPLACE SCHEMA SCH_UK_KISSOVAT;
CREATE OR REPLACE USER UK_KISSOVAT PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'kissovate@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_KISSOVAT'; 
 
CREATE OR REPLACE ROLE ROLE_UK_KNIESOVAM;
CREATE OR REPLACE SCHEMA SCH_UK_KNIESOVAM;
CREATE OR REPLACE USER UK_KNIESOVAM PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'kniesovm@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_KNIESOVAM'; 
 
CREATE OR REPLACE ROLE ROLE_UK_KREJCIRD;
CREATE OR REPLACE SCHEMA SCH_UK_KREJCIRD;
CREATE OR REPLACE USER UK_KREJCIRD PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'krejcirdav@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_KREJCIRD'; 
 
CREATE OR REPLACE ROLE ROLE_UK_MRACEKJ;
CREATE OR REPLACE SCHEMA SCH_UK_MRACEKJ;
CREATE OR REPLACE USER UK_MRACEKJ PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'mracekjan@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_MRACEKJ'; 
 
CREATE OR REPLACE ROLE ROLE_UK_NAVARAV;
CREATE OR REPLACE SCHEMA SCH_UK_NAVARAV;
CREATE OR REPLACE USER UK_NAVARAV PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'navaravi@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_NAVARAV'; 
 
CREATE OR REPLACE ROLE ROLE_UK_NOVAKF;
CREATE OR REPLACE SCHEMA SCH_UK_NOVAKF;
CREATE OR REPLACE USER UK_NOVAKF PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'novakfilip9@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_NOVAKF'; 
 
CREATE OR REPLACE ROLE ROLE_UK_PUNGEO;
CREATE OR REPLACE SCHEMA SCH_UK_PUNGEO;
CREATE OR REPLACE USER UK_PUNGEO PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'pungeo@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_PUNGEO'; 
 
CREATE OR REPLACE ROLE ROLE_UK_SEDLAKO;
CREATE OR REPLACE SCHEMA SCH_UK_SEDLAKO;
CREATE OR REPLACE USER UK_SEDLAKO PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'sondrej18@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_SEDLAKO'; 
 
CREATE OR REPLACE ROLE ROLE_UK_BARTONA;
CREATE OR REPLACE SCHEMA SCH_UK_BARTONA;
CREATE OR REPLACE USER UK_BARTONA PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'bartonada@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_BARTONA'; 
 
CREATE OR REPLACE ROLE ROLE_UK_CEPEKJ;
CREATE OR REPLACE SCHEMA SCH_UK_CEPEKJ;
CREATE OR REPLACE USER UK_CEPEKJ PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'chachustvc@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_CEPEKJ'; 
 
CREATE OR REPLACE ROLE ROLE_UK_INDRAR;
CREATE OR REPLACE SCHEMA SCH_UK_INDRAR;
CREATE OR REPLACE USER UK_INDRAR PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'indrar@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_INDRAR'; 
 
CREATE OR REPLACE ROLE ROLE_UK_KRALOVAV;
CREATE OR REPLACE SCHEMA SCH_UK_KRALOVAV;
CREATE OR REPLACE USER UK_KRALOVAV PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'verkakr@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_KRALOVAV'; 
 
CREATE OR REPLACE ROLE ROLE_UK_MLYNARJ;
CREATE OR REPLACE SCHEMA SCH_UK_MLYNARJ;
CREATE OR REPLACE USER UK_MLYNARJ PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'mlynarjar@naur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_MLYNARJ'; 
 
CREATE OR REPLACE ROLE ROLE_UK_PADIVYV;
CREATE OR REPLACE SCHEMA SCH_UK_PADIVYV;
CREATE OR REPLACE USER UK_PADIVYV PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'v.padivy@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_PADIVYV'; 
 
CREATE OR REPLACE ROLE ROLE_UK_PTACKOVAE;
CREATE OR REPLACE SCHEMA SCH_UK_PTACKOVAE;
CREATE OR REPLACE USER UK_PTACKOVAE PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'ptackovel@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_PTACKOVAE'; 
 
CREATE OR REPLACE ROLE ROLE_UK_RUZICKOVAK;
CREATE OR REPLACE SCHEMA SCH_UK_RUZICKOVAK;
CREATE OR REPLACE USER UK_RUZICKOVAK PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'kackaruzickova04@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_RUZICKOVAK'; 
 
CREATE OR REPLACE ROLE ROLE_UK_SEBEKD;
CREATE OR REPLACE SCHEMA SCH_UK_SEBEKD;
CREATE OR REPLACE USER UK_SEBEKD PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'davidsebek2@seznam.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_SEBEKD'; 
 
CREATE OR REPLACE ROLE ROLE_UK_SEDIVYJ;
CREATE OR REPLACE SCHEMA SCH_UK_SEDIVYJ;
CREATE OR REPLACE USER UK_SEDIVYJ PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'sedivyjon@natur.cuni.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_SEDIVYJ'; 
 
CREATE OR REPLACE ROLE ROLE_UK_TRANN;
CREATE OR REPLACE SCHEMA SCH_UK_TRANN;
CREATE OR REPLACE USER UK_TRANN PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'alzinkatran@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_TRANN'; 
 
CREATE OR REPLACE ROLE ROLE_UK_VOSTROVSKAD;
CREATE OR REPLACE SCHEMA SCH_UK_VOSTROVSKAD;
CREATE OR REPLACE USER UK_VOSTROVSKAD PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'dora.vostrovska66@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_UK', DEFAULT_ROLE = 'ROLE_UK_VOSTROVSKAD'; 
-- GRANTNUTI PRAV KOUCUM PRO NODE UK; 
GRANT ROLE ROLE_UK_KOUC TO ROLE ROLE_SUPERKOUC; 
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_KOUC; 
 /*UNCOMMENT AT WILL 
-- ROLES FOR UK
GRANT ROLE ROLE_UK_KOUC TO USER KOUC_KOUC; 
UNCOMMENT AT WILL */ 

--GRANT SELECT ON SCHEMAS TO ROLES 
GRANT USAGE ON DATABASE COURSES TO ROLE ROLE_UK; 
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_UK; 
GRANT USAGE ON SCHEMA COURSES.SCH_UK TO ROLE ROLE_UK; 
GRANT SELECT ON ALL TABLES IN SCHEMA COURSES.SCH_UK TO ROLE ROLE_UK; 
GRANT SELECT ON FUTURE TABLES IN SCHEMA COURSES.SCH_UK TO ROLE ROLE_UK; 
GRANT USAGE ON SCHEMA COURSES.SCH_UK_HRISTE TO ROLE ROLE_UK; 
GRANT SELECT ON ALL TABLES IN SCHEMA COURSES.SCH_UK_HRISTE TO ROLE ROLE_UK; 
GRANT SELECT ON FUTURE TABLES IN SCHEMA COURSES.SCH_UK_HRISTE TO ROLE ROLE_UK; 
GRANT ALL ON SCHEMA COURSES.SCH_UK TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA COURSES.SCH_UK TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA COURSES.SCH_UK TO ROLE ROLE_UK_KOUC; 


GRANT USAGE ON DATABASE UK_COURSES TO ROLE ROLE_UK; 
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_UK; 
GRANT USAGE ON SCHEMA COURSES.SCH_UK TO ROLE ROLE_UK; 
GRANT SELECT ON ALL TABLES IN SCHEMA UK_COURSES.SCH_UK TO ROLE ROLE_UK; 
GRANT SELECT ON FUTURE TABLES IN SCHEMA UK_COURSES.SCH_UK TO ROLE ROLE_UK; 
GRANT USAGE ON SCHEMA UK_COURSES.SCH_UK_HRISTE TO ROLE ROLE_UK; 
GRANT SELECT ON ALL TABLES IN SCHEMA UK_COURSES.SCH_UK_HRISTE TO ROLE ROLE_UK; 
GRANT SELECT ON FUTURE TABLES IN SCHEMA UK_COURSES.SCH_UK_HRISTE TO ROLE ROLE_UK; 



GRANT ROLE ROLE_UK TO ROLE ROLE_UK_STRYKAV;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_HORCIKJ;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_KVASNICKOVAL;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_MAIEROVAT;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_MASICKOVAK;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_SENOHRABKOVAE;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_TRINHM;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_VESELAP;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_VOKOUNOVAT;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_VYSKOCOVAK;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_ADAMEKJ;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_BARTOSV;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_HRUSKOVAZ;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_JANDIKJ;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_JINDROVAA;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_KISSOVAT;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_KNIESOVAM;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_KREJCIRD;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_MRACEKJ;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_NAVARAV;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_NOVAKF;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_PUNGEO;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_SEDLAKO;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_BARTONA;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_CEPEKJ;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_INDRAR;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_KRALOVAV;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_MLYNARJ;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_PADIVYV;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_PTACKOVAE;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_RUZICKOVAK;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_SEBEKD;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_SEDIVYJ;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_TRANN;
GRANT ROLE ROLE_UK TO ROLE ROLE_UK_VOSTROVSKAD;
GRANT ALL ON SCHEMA SCH_UK_STRYKAV TO ROLE ROLE_UK_STRYKAV; 
GRANT ROLE ROLE_UK_STRYKAV TO USER UK_STRYKAV; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_STRYKAV TO ROLE ROLE_UK_STRYKAV; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_STRYKAV TO ROLE ROLE_UK_STRYKAV; 
GRANT ALL ON SCHEMA SCH_UK_STRYKAV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_STRYKAV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_STRYKAV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_HORCIKJ TO ROLE ROLE_UK_HORCIKJ; 
GRANT ROLE ROLE_UK_HORCIKJ TO USER UK_HORCIKJ; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_HORCIKJ TO ROLE ROLE_UK_HORCIKJ; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_HORCIKJ TO ROLE ROLE_UK_HORCIKJ; 
GRANT ALL ON SCHEMA SCH_UK_HORCIKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_HORCIKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_HORCIKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_KVASNICKOVAL TO ROLE ROLE_UK_KVASNICKOVAL; 
GRANT ROLE ROLE_UK_KVASNICKOVAL TO USER UK_KVASNICKOVAL; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_KVASNICKOVAL TO ROLE ROLE_UK_KVASNICKOVAL; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_KVASNICKOVAL TO ROLE ROLE_UK_KVASNICKOVAL; 
GRANT ALL ON SCHEMA SCH_UK_KVASNICKOVAL TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_KVASNICKOVAL TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_KVASNICKOVAL TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_MAIEROVAT TO ROLE ROLE_UK_MAIEROVAT; 
GRANT ROLE ROLE_UK_MAIEROVAT TO USER UK_MAIEROVAT; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_MAIEROVAT TO ROLE ROLE_UK_MAIEROVAT; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_MAIEROVAT TO ROLE ROLE_UK_MAIEROVAT; 
GRANT ALL ON SCHEMA SCH_UK_MAIEROVAT TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_MAIEROVAT TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_MAIEROVAT TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_MASICKOVAK TO ROLE ROLE_UK_MASICKOVAK; 
GRANT ROLE ROLE_UK_MASICKOVAK TO USER UK_MASICKOVAK; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_MASICKOVAK TO ROLE ROLE_UK_MASICKOVAK; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_MASICKOVAK TO ROLE ROLE_UK_MASICKOVAK; 
GRANT ALL ON SCHEMA SCH_UK_MASICKOVAK TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_MASICKOVAK TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_MASICKOVAK TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_SENOHRABKOVAE TO ROLE ROLE_UK_SENOHRABKOVAE; 
GRANT ROLE ROLE_UK_SENOHRABKOVAE TO USER UK_SENOHRABKOVAE; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_SENOHRABKOVAE TO ROLE ROLE_UK_SENOHRABKOVAE; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_SENOHRABKOVAE TO ROLE ROLE_UK_SENOHRABKOVAE; 
GRANT ALL ON SCHEMA SCH_UK_SENOHRABKOVAE TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_SENOHRABKOVAE TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_SENOHRABKOVAE TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_TRINHM TO ROLE ROLE_UK_TRINHM; 
GRANT ROLE ROLE_UK_TRINHM TO USER UK_TRINHM; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_TRINHM TO ROLE ROLE_UK_TRINHM; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_TRINHM TO ROLE ROLE_UK_TRINHM; 
GRANT ALL ON SCHEMA SCH_UK_TRINHM TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_TRINHM TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_TRINHM TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_VESELAP TO ROLE ROLE_UK_VESELAP; 
GRANT ROLE ROLE_UK_VESELAP TO USER UK_VESELAP; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_VESELAP TO ROLE ROLE_UK_VESELAP; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_VESELAP TO ROLE ROLE_UK_VESELAP; 
GRANT ALL ON SCHEMA SCH_UK_VESELAP TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_VESELAP TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_VESELAP TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_VOKOUNOVAT TO ROLE ROLE_UK_VOKOUNOVAT; 
GRANT ROLE ROLE_UK_VOKOUNOVAT TO USER UK_VOKOUNOVAT; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_VOKOUNOVAT TO ROLE ROLE_UK_VOKOUNOVAT; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_VOKOUNOVAT TO ROLE ROLE_UK_VOKOUNOVAT; 
GRANT ALL ON SCHEMA SCH_UK_VOKOUNOVAT TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_VOKOUNOVAT TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_VOKOUNOVAT TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_VYSKOCOVAK TO ROLE ROLE_UK_VYSKOCOVAK; 
GRANT ROLE ROLE_UK_VYSKOCOVAK TO USER UK_VYSKOCOVAK; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_VYSKOCOVAK TO ROLE ROLE_UK_VYSKOCOVAK; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_VYSKOCOVAK TO ROLE ROLE_UK_VYSKOCOVAK; 
GRANT ALL ON SCHEMA SCH_UK_VYSKOCOVAK TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_VYSKOCOVAK TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_VYSKOCOVAK TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_ADAMEKJ TO ROLE ROLE_UK_ADAMEKJ; 
GRANT ROLE ROLE_UK_ADAMEKJ TO USER UK_ADAMEKJ; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_ADAMEKJ TO ROLE ROLE_UK_ADAMEKJ; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_ADAMEKJ TO ROLE ROLE_UK_ADAMEKJ; 
GRANT ALL ON SCHEMA SCH_UK_ADAMEKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_ADAMEKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_ADAMEKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_BARTOSV TO ROLE ROLE_UK_BARTOSV; 
GRANT ROLE ROLE_UK_BARTOSV TO USER UK_BARTOSV; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_BARTOSV TO ROLE ROLE_UK_BARTOSV; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_BARTOSV TO ROLE ROLE_UK_BARTOSV; 
GRANT ALL ON SCHEMA SCH_UK_BARTOSV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_BARTOSV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_BARTOSV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_HRUSKOVAZ TO ROLE ROLE_UK_HRUSKOVAZ; 
GRANT ROLE ROLE_UK_HRUSKOVAZ TO USER UK_HRUSKOVAZ; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_HRUSKOVAZ TO ROLE ROLE_UK_HRUSKOVAZ; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_HRUSKOVAZ TO ROLE ROLE_UK_HRUSKOVAZ; 
GRANT ALL ON SCHEMA SCH_UK_HRUSKOVAZ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_HRUSKOVAZ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_HRUSKOVAZ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_JANDIKJ TO ROLE ROLE_UK_JANDIKJ; 
GRANT ROLE ROLE_UK_JANDIKJ TO USER UK_JANDIKJ; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_JANDIKJ TO ROLE ROLE_UK_JANDIKJ; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_JANDIKJ TO ROLE ROLE_UK_JANDIKJ; 
GRANT ALL ON SCHEMA SCH_UK_JANDIKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_JANDIKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_JANDIKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_JINDROVAA TO ROLE ROLE_UK_JINDROVAA; 
GRANT ROLE ROLE_UK_JINDROVAA TO USER UK_JINDROVAA; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_JINDROVAA TO ROLE ROLE_UK_JINDROVAA; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_JINDROVAA TO ROLE ROLE_UK_JINDROVAA; 
GRANT ALL ON SCHEMA SCH_UK_JINDROVAA TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_JINDROVAA TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_JINDROVAA TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_KISSOVAT TO ROLE ROLE_UK_KISSOVAT; 
GRANT ROLE ROLE_UK_KISSOVAT TO USER UK_KISSOVAT; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_KISSOVAT TO ROLE ROLE_UK_KISSOVAT; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_KISSOVAT TO ROLE ROLE_UK_KISSOVAT; 
GRANT ALL ON SCHEMA SCH_UK_KISSOVAT TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_KISSOVAT TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_KISSOVAT TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_KNIESOVAM TO ROLE ROLE_UK_KNIESOVAM; 
GRANT ROLE ROLE_UK_KNIESOVAM TO USER UK_KNIESOVAM; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_KNIESOVAM TO ROLE ROLE_UK_KNIESOVAM; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_KNIESOVAM TO ROLE ROLE_UK_KNIESOVAM; 
GRANT ALL ON SCHEMA SCH_UK_KNIESOVAM TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_KNIESOVAM TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_KNIESOVAM TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_KREJCIRD TO ROLE ROLE_UK_KREJCIRD; 
GRANT ROLE ROLE_UK_KREJCIRD TO USER UK_KREJCIRD; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_KREJCIRD TO ROLE ROLE_UK_KREJCIRD; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_KREJCIRD TO ROLE ROLE_UK_KREJCIRD; 
GRANT ALL ON SCHEMA SCH_UK_KREJCIRD TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_KREJCIRD TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_KREJCIRD TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_MRACEKJ TO ROLE ROLE_UK_MRACEKJ; 
GRANT ROLE ROLE_UK_MRACEKJ TO USER UK_MRACEKJ; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_MRACEKJ TO ROLE ROLE_UK_MRACEKJ; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_MRACEKJ TO ROLE ROLE_UK_MRACEKJ; 
GRANT ALL ON SCHEMA SCH_UK_MRACEKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_MRACEKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_MRACEKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_NAVARAV TO ROLE ROLE_UK_NAVARAV; 
GRANT ROLE ROLE_UK_NAVARAV TO USER UK_NAVARAV; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_NAVARAV TO ROLE ROLE_UK_NAVARAV; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_NAVARAV TO ROLE ROLE_UK_NAVARAV; 
GRANT ALL ON SCHEMA SCH_UK_NAVARAV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_NAVARAV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_NAVARAV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_NOVAKF TO ROLE ROLE_UK_NOVAKF; 
GRANT ROLE ROLE_UK_NOVAKF TO USER UK_NOVAKF; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_NOVAKF TO ROLE ROLE_UK_NOVAKF; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_NOVAKF TO ROLE ROLE_UK_NOVAKF; 
GRANT ALL ON SCHEMA SCH_UK_NOVAKF TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_NOVAKF TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_NOVAKF TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_PUNGEO TO ROLE ROLE_UK_PUNGEO; 
GRANT ROLE ROLE_UK_PUNGEO TO USER UK_PUNGEO; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_PUNGEO TO ROLE ROLE_UK_PUNGEO; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_PUNGEO TO ROLE ROLE_UK_PUNGEO; 
GRANT ALL ON SCHEMA SCH_UK_PUNGEO TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_PUNGEO TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_PUNGEO TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_SEDLAKO TO ROLE ROLE_UK_SEDLAKO; 
GRANT ROLE ROLE_UK_SEDLAKO TO USER UK_SEDLAKO; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_SEDLAKO TO ROLE ROLE_UK_SEDLAKO; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_SEDLAKO TO ROLE ROLE_UK_SEDLAKO; 
GRANT ALL ON SCHEMA SCH_UK_SEDLAKO TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_SEDLAKO TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_SEDLAKO TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_BARTONA TO ROLE ROLE_UK_BARTONA; 
GRANT ROLE ROLE_UK_BARTONA TO USER UK_BARTONA; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_BARTONA TO ROLE ROLE_UK_BARTONA; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_BARTONA TO ROLE ROLE_UK_BARTONA; 
GRANT ALL ON SCHEMA SCH_UK_BARTONA TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_BARTONA TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_BARTONA TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_CEPEKJ TO ROLE ROLE_UK_CEPEKJ; 
GRANT ROLE ROLE_UK_CEPEKJ TO USER UK_CEPEKJ; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_CEPEKJ TO ROLE ROLE_UK_CEPEKJ; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_CEPEKJ TO ROLE ROLE_UK_CEPEKJ; 
GRANT ALL ON SCHEMA SCH_UK_CEPEKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_CEPEKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_CEPEKJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_INDRAR TO ROLE ROLE_UK_INDRAR; 
GRANT ROLE ROLE_UK_INDRAR TO USER UK_INDRAR; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_INDRAR TO ROLE ROLE_UK_INDRAR; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_INDRAR TO ROLE ROLE_UK_INDRAR; 
GRANT ALL ON SCHEMA SCH_UK_INDRAR TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_INDRAR TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_INDRAR TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_KRALOVAV TO ROLE ROLE_UK_KRALOVAV; 
GRANT ROLE ROLE_UK_KRALOVAV TO USER UK_KRALOVAV; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_KRALOVAV TO ROLE ROLE_UK_KRALOVAV; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_KRALOVAV TO ROLE ROLE_UK_KRALOVAV; 
GRANT ALL ON SCHEMA SCH_UK_KRALOVAV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_KRALOVAV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_KRALOVAV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_MLYNARJ TO ROLE ROLE_UK_MLYNARJ; 
GRANT ROLE ROLE_UK_MLYNARJ TO USER UK_MLYNARJ; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_MLYNARJ TO ROLE ROLE_UK_MLYNARJ; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_MLYNARJ TO ROLE ROLE_UK_MLYNARJ; 
GRANT ALL ON SCHEMA SCH_UK_MLYNARJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_MLYNARJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_MLYNARJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_PADIVYV TO ROLE ROLE_UK_PADIVYV; 
GRANT ROLE ROLE_UK_PADIVYV TO USER UK_PADIVYV; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_PADIVYV TO ROLE ROLE_UK_PADIVYV; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_PADIVYV TO ROLE ROLE_UK_PADIVYV; 
GRANT ALL ON SCHEMA SCH_UK_PADIVYV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_PADIVYV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_PADIVYV TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_PTACKOVAE TO ROLE ROLE_UK_PTACKOVAE; 
GRANT ROLE ROLE_UK_PTACKOVAE TO USER UK_PTACKOVAE; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_PTACKOVAE TO ROLE ROLE_UK_PTACKOVAE; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_PTACKOVAE TO ROLE ROLE_UK_PTACKOVAE; 
GRANT ALL ON SCHEMA SCH_UK_PTACKOVAE TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_PTACKOVAE TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_PTACKOVAE TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_RUZICKOVAK TO ROLE ROLE_UK_RUZICKOVAK; 
GRANT ROLE ROLE_UK_RUZICKOVAK TO USER UK_RUZICKOVAK; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_RUZICKOVAK TO ROLE ROLE_UK_RUZICKOVAK; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_RUZICKOVAK TO ROLE ROLE_UK_RUZICKOVAK; 
GRANT ALL ON SCHEMA SCH_UK_RUZICKOVAK TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_RUZICKOVAK TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_RUZICKOVAK TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_SEBEKD TO ROLE ROLE_UK_SEBEKD; 
GRANT ROLE ROLE_UK_SEBEKD TO USER UK_SEBEKD; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_SEBEKD TO ROLE ROLE_UK_SEBEKD; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_SEBEKD TO ROLE ROLE_UK_SEBEKD; 
GRANT ALL ON SCHEMA SCH_UK_SEBEKD TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_SEBEKD TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_SEBEKD TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_SEDIVYJ TO ROLE ROLE_UK_SEDIVYJ; 
GRANT ROLE ROLE_UK_SEDIVYJ TO USER UK_SEDIVYJ; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_SEDIVYJ TO ROLE ROLE_UK_SEDIVYJ; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_SEDIVYJ TO ROLE ROLE_UK_SEDIVYJ; 
GRANT ALL ON SCHEMA SCH_UK_SEDIVYJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_SEDIVYJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_SEDIVYJ TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_TRANN TO ROLE ROLE_UK_TRANN; 
GRANT ROLE ROLE_UK_TRANN TO USER UK_TRANN; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_TRANN TO ROLE ROLE_UK_TRANN; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_TRANN TO ROLE ROLE_UK_TRANN; 
GRANT ALL ON SCHEMA SCH_UK_TRANN TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_TRANN TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_TRANN TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON SCHEMA SCH_UK_VOSTROVSKAD TO ROLE ROLE_UK_VOSTROVSKAD; 
GRANT ROLE ROLE_UK_VOSTROVSKAD TO USER UK_VOSTROVSKAD; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_VOSTROVSKAD TO ROLE ROLE_UK_VOSTROVSKAD; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_VOSTROVSKAD TO ROLE ROLE_UK_VOSTROVSKAD; 
GRANT ALL ON SCHEMA SCH_UK_VOSTROVSKAD TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_UK_VOSTROVSKAD TO ROLE ROLE_UK_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_UK_VOSTROVSKAD TO ROLE ROLE_UK_KOUC; 
