--this is generated login file 
CREATE OR REPLACE ROLE ROLE_SUPERKOUC; 
GRANT ROLE ROLE_SUPERKOUC TO USER sfadmin; 
CREATE OR REPLACE ROLE ROLE_KOUC; 
GRANT USAGE ON DATABASE COURSES TO ROLE ROLE_KOUC; 
/* * * * * * * *  * * * * **********************************/ 
--VYTVORENI KOUCUCREATE OR REPLACE USER KOUC_KOUC PASSWORD = 'SpANEKSeNePRECENUJE', EMAIL = 'pavel@chocholous.net', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.PUBLIC', DEFAULT_ROLE = 'ROLE_KOUC'; 
GRANT ROLE ROLE_KOUC TO USER KOUC_KOUC; 

--USER LOGIN, SCHEMA, ROLE 
-- VYTVORENI SCHEMAT A ROLI NODE CZECHITA; 
CREATE OR REPLACE ROLE ROLE_CZECHITA; 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KOUC; 
CREATE OR REPLACE SCHEMA SCH_CZECHITA; 
CREATE OR REPLACE SCHEMA SCH_CZECHITA_HRISTE; 
create or replace TABLE SCH_CZECHITA.TEROR_DPJ22 (   EVENTID NUMBER(38,0),   IYEAR NUMBER(38,0),   IMONTH NUMBER(38,0),   IDAY NUMBER(38,0),   APPROXDATE VARCHAR(16777216),   EXTENDED NUMBER(38,0),   RESOLUTION NUMBER(38,0),   COUNTRY NUMBER(38,0),   COUNTRY_TXT VARCHAR(16777216),   REGION NUMBER(38,0),   REGION_TXT VARCHAR(16777216),   PROVSTATE VARCHAR(16777216),   CITY VARCHAR(16777216),   LATITUDE NUMBER(12,8),   LONGITUDE NUMBER(12,8),   SPECIFICITY NUMBER(38,0),   VICINITY NUMBER(38,0),   LOCATION VARCHAR(16777216),   SUMMARY VARCHAR(16777216),   CRIT1 NUMBER(38,0),   CRIT2 NUMBER(38,0),   CRIT3 NUMBER(38,0),   DOUBTTERR NUMBER(38,0),   ALTERNATIVE NUMBER(38,0),   ALTERNATIVE_TXT VARCHAR(16777216),   MULTIPLE NUMBER(38,0),   SUCCESS NUMBER(38,0),   SUICIDE NUMBER(38,0),   ATTACKTYPE1 NUMBER(38,0),   ATTACKTYPE1_TXT VARCHAR(16777216),   ATTACKTYPE2 NUMBER(38,0),   ATTACKTYPE2_TXT VARCHAR(16777216),   ATTACKTYPE3 NUMBER(38,0),   ATTACKTYPE3_TXT VARCHAR(16777216),   TARGTYPE1 NUMBER(38,0),   TARGTYPE1_TXT VARCHAR(16777216),   TARGSUBTYPE1 NUMBER(38,0),   TARGSUBTYPE1_TXT VARCHAR(16777216),   CORP1 VARCHAR(16777216),   TARGET1 VARCHAR(16777216),   NATLTY1 NUMBER(38,0),   NATLTY1_TXT VARCHAR(16777216),   TARGTYPE2 NUMBER(38,0),   TARGTYPE2_TXT VARCHAR(16777216),   TARGSUBTYPE2 NUMBER(38,0),   TARGSUBTYPE2_TXT VARCHAR(16777216),   CORP2 VARCHAR(16777216),   TARGET2 VARCHAR(16777216),   NATLTY2 NUMBER(38,0),   NATLTY2_TXT VARCHAR(16777216),   TARGTYPE3 NUMBER(38,0),   TARGTYPE3_TXT VARCHAR(16777216),   TARGSUBTYPE3 NUMBER(38,0),   TARGSUBTYPE3_TXT VARCHAR(16777216),   CORP3 VARCHAR(16777216),   TARGET3 VARCHAR(16777216),   NATLTY3 NUMBER(38,0),   NATLTY3_TXT VARCHAR(16777216),   GNAME VARCHAR(16777216),   GSUBNAME VARCHAR(16777216),   GNAME2 VARCHAR(16777216),   GSUBNAME2 VARCHAR(16777216),   GNAME3 VARCHAR(16777216),   GSUBNAME3 VARCHAR(16777216),   MOTIVE VARCHAR(16777216),   GUNCERTAIN1 NUMBER(38,0),   GUNCERTAIN2 NUMBER(38,0),   GUNCERTAIN3 NUMBER(38,0),   INDIVIDUAL NUMBER(38,0),   NPERPS NUMBER(38,0),   NPERPCAP NUMBER(38,0),   CLAIMED NUMBER(38,0),   CLAIMMODE NUMBER(38,0),   CLAIMMODE_TXT VARCHAR(16777216),   CLAIM2 VARCHAR(16777216),   CLAIMMODE2 VARCHAR(16777216),   CLAIMMODE2_TXT VARCHAR(16777216),   CLAIM3 VARCHAR(16777216),   CLAIMMODE3 VARCHAR(16777216),   CLAIMMODE3_TXT VARCHAR(16777216),   COMPCLAIM VARCHAR(16777216),   WEAPTYPE1 NUMBER(38,0),   WEAPTYPE1_TXT VARCHAR(16777216),   WEAPSUBTYPE1 NUMBER(38,0),   WEAPSUBTYPE1_TXT VARCHAR(16777216),   WEAPTYPE2 NUMBER(38,0),   WEAPTYPE2_TXT VARCHAR(16777216),   WEAPSUBTYPE2 NUMBER(38,0),   WEAPSUBTYPE2_TXT VARCHAR(16777216),   WEAPTYPE3 NUMBER(38,0),   WEAPTYPE3_TXT VARCHAR(16777216),   WEAPSUBTYPE3 NUMBER(38,0),   WEAPSUBTYPE3_TXT VARCHAR(16777216),   WEAPTYPE4 NUMBER(38,0),   WEAPTYPE4_TXT VARCHAR(16777216),   WEAPSUBTYPE4 NUMBER(38,0),   WEAPSUBTYPE4_TXT VARCHAR(16777216),   WEAPDETAIL VARCHAR(16777216),   NKILL NUMBER(38,0),   NKILLUS NUMBER(38,0),   NKILLTER NUMBER(38,0),   NWOUND NUMBER(38,0),   NWOUNDUS NUMBER(38,0),   NWOUNDTE NUMBER(38,0),   PROPERTY NUMBER(38,0),   PROPEXTENT NUMBER(38,0),   PROPEXTENT_TXT VARCHAR(16777216),   PROPVALUE NUMBER(38,0),   PROPCOMMENT VARCHAR(16777216),   ISHOSTKID NUMBER(38,0),   NHOSTKID NUMBER(38,0),   NHOSTKIDUS NUMBER(38,0),   NHOURS NUMBER(38,0),   NDAYS NUMBER(38,0),   DIVERT VARCHAR(16777216),   KIDHIJCOUNTRY VARCHAR(16777216),   RANSOM NUMBER(38,0),   RANSOMAMT NUMBER(16,4),   RANSOMAMTUS NUMBER(16,4),   RANSOMPAID NUMBER(16,4),   RANSOMPAIDUS NUMBER(16,4),   RANSOMNOTE VARCHAR(16777216),   HOSTKIDOUTCOME NUMBER(38,0),   HOSTKIDOUTCOME_TXT VARCHAR(16777216),   NRELEASED NUMBER(38,0),   ADDNOTES VARCHAR(16777216),   SCITE1 VARCHAR(16777216),   SCITE2 VARCHAR(16777216),   SCITE3 VARCHAR(16777216),   DBSOURCE VARCHAR(16777216),   INT_LOG NUMBER(38,0),   INT_IDEO NUMBER(38,0),   INT_MISC NUMBER(38,0),   INT_ANY NUMBER(38,0),   RELATED VARCHAR(16777216)  ); 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_STESTI;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_STESTI;
CREATE OR REPLACE USER CZECHITA_STESTI PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'pavel@chocholous.net', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_STESTI'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_AICHINGERA;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_AICHINGERA;
CREATE OR REPLACE USER CZECHITA_AICHINGERA PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'aja.jankovska@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_AICHINGERA'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_BESTOVAK;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_BESTOVAK;
CREATE OR REPLACE USER CZECHITA_BESTOVAK PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'kristyna.bestova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_BESTOVAK'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_BUBENICKOVAP;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_BUBENICKOVAP;
CREATE OR REPLACE USER CZECHITA_BUBENICKOVAP PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'krokwe@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_BUBENICKOVAP'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_CERNAE;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_CERNAE;
CREATE OR REPLACE USER CZECHITA_CERNAE PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'cerna@znzelectronics.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_CERNAE'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_DE ACETISK;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_DE ACETISK;
CREATE OR REPLACE USER CZECHITA_DE ACETISK PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'katerina.deacetis@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_DE ACETISK'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_DOUBRAVOVAL;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_DOUBRAVOVAL;
CREATE OR REPLACE USER CZECHITA_DOUBRAVOVAL PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'wendelinka.lenka@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_DOUBRAVOVAL'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_DVORAKOVAS;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_DVORAKOVAS;
CREATE OR REPLACE USER CZECHITA_DVORAKOVAS PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'dvorakovasara@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_DVORAKOVAS'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_FLIEGEROVAP;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_FLIEGEROVAP;
CREATE OR REPLACE USER CZECHITA_FLIEGEROVAP PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'petra.fliegerova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_FLIEGEROVAP'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_HLAVINOVAB;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_HLAVINOVAB;
CREATE OR REPLACE USER CZECHITA_HLAVINOVAB PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'hlavinova.bara@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_HLAVINOVAB'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_HRNCALOVAM;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_HRNCALOVAM;
CREATE OR REPLACE USER CZECHITA_HRNCALOVAM PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'marcela.hrncalova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_HRNCALOVAM'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_JASURKOVAM;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_JASURKOVAM;
CREATE OR REPLACE USER CZECHITA_JASURKOVAM PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'jasurkova.m1@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_JASURKOVAM'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_JIMENEZL;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_JIMENEZL;
CREATE OR REPLACE USER CZECHITA_JIMENEZL PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'lucie.jimenez@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_JIMENEZL'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KALAFUTOVAN;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KALAFUTOVAN;
CREATE OR REPLACE USER CZECHITA_KALAFUTOVAN PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'natalia.kalafutova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KALAFUTOVAN'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KOCOURKOVAE;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KOCOURKOVAE;
CREATE OR REPLACE USER CZECHITA_KOCOURKOVAE PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'efkocourkova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KOCOURKOVAE'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KOLAROVAM;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KOLAROVAM;
CREATE OR REPLACE USER CZECHITA_KOLAROVAM PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'kolarova.mi@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KOLAROVAM'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_KUNCOVAI;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_KUNCOVAI;
CREATE OR REPLACE USER CZECHITA_KUNCOVAI PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'vtkncv@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_KUNCOVAI'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_MARKOVAP;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_MARKOVAP;
CREATE OR REPLACE USER CZECHITA_MARKOVAP PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'markova.petulda@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_MARKOVAP'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_MORAVCOVAM;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_MORAVCOVAM;
CREATE OR REPLACE USER CZECHITA_MORAVCOVAM PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'MartinaMoravcova84.MM@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_MORAVCOVAM'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_NOVAKOVAK;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_NOVAKOVAK;
CREATE OR REPLACE USER CZECHITA_NOVAKOVAK PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'katerina.p.novakova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_NOVAKOVAK'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_NOVOSILSKAO;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_NOVOSILSKAO;
CREATE OR REPLACE USER CZECHITA_NOVOSILSKAO PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'olha.novosilska@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_NOVOSILSKAO'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_NUTELSY;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_NUTELSY;
CREATE OR REPLACE USER CZECHITA_NUTELSY PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'yulianutels@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_NUTELSY'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_PARASKEVAO;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_PARASKEVAO;
CREATE OR REPLACE USER CZECHITA_PARASKEVAO PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'oksanaparaskeva@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_PARASKEVAO'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_PECHERSKAA;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_PECHERSKAA;
CREATE OR REPLACE USER CZECHITA_PECHERSKAA PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'helenkamiller01@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_PECHERSKAA'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_PRUCHOVAK;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_PRUCHOVAK;
CREATE OR REPLACE USER CZECHITA_PRUCHOVAK PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'kl.pruchova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_PRUCHOVAK'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_PUZMANOVAM;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_PUZMANOVAM;
CREATE OR REPLACE USER CZECHITA_PUZMANOVAM PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'cardovamichaela@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_PUZMANOVAM'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_REZLEROVAI;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_REZLEROVAI;
CREATE OR REPLACE USER CZECHITA_REZLEROVAI PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'polackova.ivca@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_REZLEROVAI'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_RIZZIN;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_RIZZIN;
CREATE OR REPLACE USER CZECHITA_RIZZIN PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'nela.rizzi.22@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_RIZZIN'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_RYBCHENKOL;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_RYBCHENKOL;
CREATE OR REPLACE USER CZECHITA_RYBCHENKOL PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'rybchenkoliliya@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_RYBCHENKOL'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_SKALOVAG;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_SKALOVAG;
CREATE OR REPLACE USER CZECHITA_SKALOVAG PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'gabrielascala20@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_SKALOVAG'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_SESTAKOVAV;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_SESTAKOVAV;
CREATE OR REPLACE USER CZECHITA_SESTAKOVAV PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'sestakova.ver@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_SESTAKOVAV'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_SMIDOVAD;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_SMIDOVAD;
CREATE OR REPLACE USER CZECHITA_SMIDOVAD PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'jafira@seznam.cz', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_SMIDOVAD'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_SVECOVAV;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_SVECOVAV;
CREATE OR REPLACE USER CZECHITA_SVECOVAV PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'veronika.klimsova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_SVECOVAV'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_VITKOVAA;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_VITKOVAA;
CREATE OR REPLACE USER CZECHITA_VITKOVAA PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'alenavitkova21@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_VITKOVAA'; 
 
CREATE OR REPLACE ROLE ROLE_CZECHITA_VOJACKOVAB;
CREATE OR REPLACE SCHEMA SCH_CZECHITA_VOJACKOVAB;
CREATE OR REPLACE USER CZECHITA_VOJACKOVAB PASSWORD = 'SpANEKSePrECENUJE', EMAIL = 'barbara.vojackova@gmail.com', MUST_CHANGE_PASSWORD = TRUE, DEFAULT_WAREHOUSE = 'COMPUTE_WH', DEFAULT_NAMESPACE = 'COURSES.SCH_CZECHITA', DEFAULT_ROLE = 'ROLE_CZECHITA_VOJACKOVAB'; 
-- GRANTNUTI PRAV KOUCUM PRO NODE CZECHITA; 
GRANT ROLE ROLE_CZECHITA_KOUC TO ROLE ROLE_SUPERKOUC; 
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KOUC; 
 /*UNCOMMENT AT WILL 
-- ROLES FOR CZECHITA
GRANT ROLE ROLE_CZECHITA_KOUC TO USER KOUC_KOUC; 
UNCOMMENT AT WILL */ 

--GRANT SELECT ON SCHEMAS TO ROLES 
GRANT USAGE ON DATABASE COURSES TO ROLE ROLE_CZECHITA; 
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_CZECHITA; 
GRANT USAGE ON SCHEMA SCH_CZECHITA TO ROLE ROLE_CZECHITA; 
GRANT SELECT ON ALL TABLES IN SCHEMA SCH_CZECHITA TO ROLE ROLE_CZECHITA; 
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCH_CZECHITA TO ROLE ROLE_CZECHITA; 
GRANT USAGE ON SCHEMA SCH_CZECHITA_HRISTE TO ROLE ROLE_CZECHITA; 
GRANT SELECT ON ALL TABLES IN SCHEMA SCH_CZECHITA_HRISTE TO ROLE ROLE_CZECHITA; 
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_HRISTE TO ROLE ROLE_CZECHITA; 
GRANT ALL ON SCHEMA SCH_CZECHITA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA TO ROLE ROLE_CZECHITA_KOUC; 
 
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_STESTI;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_AICHINGERA;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_BESTOVAK;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_BUBENICKOVAP;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_CERNAE;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_DE ACETISK;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_DOUBRAVOVAL;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_DVORAKOVAS;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_FLIEGEROVAP;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_HLAVINOVAB;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_HRNCALOVAM;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_JASURKOVAM;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_JIMENEZL;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KALAFUTOVAN;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KOCOURKOVAE;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KOLAROVAM;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_KUNCOVAI;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_MARKOVAP;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_MORAVCOVAM;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_NOVAKOVAK;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_NOVOSILSKAO;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_NUTELSY;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_PARASKEVAO;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_PECHERSKAA;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_PRUCHOVAK;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_PUZMANOVAM;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_REZLEROVAI;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_RIZZIN;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_RYBCHENKOL;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_SKALOVAG;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_SESTAKOVAV;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_SMIDOVAD;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_SVECOVAV;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_VITKOVAA;
GRANT ROLE ROLE_CZECHITA TO ROLE ROLE_CZECHITA_VOJACKOVAB;
GRANT ALL ON SCHEMA SCH_CZECHITA_STESTI TO ROLE ROLE_CZECHITA_STESTI; 
GRANT ROLE ROLE_CZECHITA_STESTI TO USER CZECHITA_STESTI; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_STESTI TO ROLE ROLE_CZECHITA_STESTI; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_STESTI TO ROLE ROLE_CZECHITA_STESTI; 
GRANT ALL ON SCHEMA SCH_CZECHITA_STESTI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_STESTI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_STESTI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_AICHINGERA TO ROLE ROLE_CZECHITA_AICHINGERA; 
GRANT ROLE ROLE_CZECHITA_AICHINGERA TO USER CZECHITA_AICHINGERA; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_AICHINGERA TO ROLE ROLE_CZECHITA_AICHINGERA; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_AICHINGERA TO ROLE ROLE_CZECHITA_AICHINGERA; 
GRANT ALL ON SCHEMA SCH_CZECHITA_AICHINGERA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_AICHINGERA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_AICHINGERA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_BESTOVAK TO ROLE ROLE_CZECHITA_BESTOVAK; 
GRANT ROLE ROLE_CZECHITA_BESTOVAK TO USER CZECHITA_BESTOVAK; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_BESTOVAK TO ROLE ROLE_CZECHITA_BESTOVAK; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_BESTOVAK TO ROLE ROLE_CZECHITA_BESTOVAK; 
GRANT ALL ON SCHEMA SCH_CZECHITA_BESTOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_BESTOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_BESTOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_BUBENICKOVAP TO ROLE ROLE_CZECHITA_BUBENICKOVAP; 
GRANT ROLE ROLE_CZECHITA_BUBENICKOVAP TO USER CZECHITA_BUBENICKOVAP; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_BUBENICKOVAP TO ROLE ROLE_CZECHITA_BUBENICKOVAP; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_BUBENICKOVAP TO ROLE ROLE_CZECHITA_BUBENICKOVAP; 
GRANT ALL ON SCHEMA SCH_CZECHITA_BUBENICKOVAP TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_BUBENICKOVAP TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_BUBENICKOVAP TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_CERNAE TO ROLE ROLE_CZECHITA_CERNAE; 
GRANT ROLE ROLE_CZECHITA_CERNAE TO USER CZECHITA_CERNAE; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_CERNAE TO ROLE ROLE_CZECHITA_CERNAE; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_CERNAE TO ROLE ROLE_CZECHITA_CERNAE; 
GRANT ALL ON SCHEMA SCH_CZECHITA_CERNAE TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_CERNAE TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_CERNAE TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_DE ACETISK TO ROLE ROLE_CZECHITA_DE ACETISK; 
GRANT ROLE ROLE_CZECHITA_DE ACETISK TO USER CZECHITA_DE ACETISK; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_DE ACETISK TO ROLE ROLE_CZECHITA_DE ACETISK; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_DE ACETISK TO ROLE ROLE_CZECHITA_DE ACETISK; 
GRANT ALL ON SCHEMA SCH_CZECHITA_DE ACETISK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_DE ACETISK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_DE ACETISK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_DOUBRAVOVAL TO ROLE ROLE_CZECHITA_DOUBRAVOVAL; 
GRANT ROLE ROLE_CZECHITA_DOUBRAVOVAL TO USER CZECHITA_DOUBRAVOVAL; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_DOUBRAVOVAL TO ROLE ROLE_CZECHITA_DOUBRAVOVAL; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_DOUBRAVOVAL TO ROLE ROLE_CZECHITA_DOUBRAVOVAL; 
GRANT ALL ON SCHEMA SCH_CZECHITA_DOUBRAVOVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_DOUBRAVOVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_DOUBRAVOVAL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_DVORAKOVAS TO ROLE ROLE_CZECHITA_DVORAKOVAS; 
GRANT ROLE ROLE_CZECHITA_DVORAKOVAS TO USER CZECHITA_DVORAKOVAS; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_DVORAKOVAS TO ROLE ROLE_CZECHITA_DVORAKOVAS; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_DVORAKOVAS TO ROLE ROLE_CZECHITA_DVORAKOVAS; 
GRANT ALL ON SCHEMA SCH_CZECHITA_DVORAKOVAS TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_DVORAKOVAS TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_DVORAKOVAS TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_FLIEGEROVAP TO ROLE ROLE_CZECHITA_FLIEGEROVAP; 
GRANT ROLE ROLE_CZECHITA_FLIEGEROVAP TO USER CZECHITA_FLIEGEROVAP; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_FLIEGEROVAP TO ROLE ROLE_CZECHITA_FLIEGEROVAP; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_FLIEGEROVAP TO ROLE ROLE_CZECHITA_FLIEGEROVAP; 
GRANT ALL ON SCHEMA SCH_CZECHITA_FLIEGEROVAP TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_FLIEGEROVAP TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_FLIEGEROVAP TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_HLAVINOVAB TO ROLE ROLE_CZECHITA_HLAVINOVAB; 
GRANT ROLE ROLE_CZECHITA_HLAVINOVAB TO USER CZECHITA_HLAVINOVAB; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_HLAVINOVAB TO ROLE ROLE_CZECHITA_HLAVINOVAB; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_HLAVINOVAB TO ROLE ROLE_CZECHITA_HLAVINOVAB; 
GRANT ALL ON SCHEMA SCH_CZECHITA_HLAVINOVAB TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_HLAVINOVAB TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_HLAVINOVAB TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_HRNCALOVAM TO ROLE ROLE_CZECHITA_HRNCALOVAM; 
GRANT ROLE ROLE_CZECHITA_HRNCALOVAM TO USER CZECHITA_HRNCALOVAM; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_HRNCALOVAM TO ROLE ROLE_CZECHITA_HRNCALOVAM; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_HRNCALOVAM TO ROLE ROLE_CZECHITA_HRNCALOVAM; 
GRANT ALL ON SCHEMA SCH_CZECHITA_HRNCALOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_HRNCALOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_HRNCALOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_JASURKOVAM TO ROLE ROLE_CZECHITA_JASURKOVAM; 
GRANT ROLE ROLE_CZECHITA_JASURKOVAM TO USER CZECHITA_JASURKOVAM; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_JASURKOVAM TO ROLE ROLE_CZECHITA_JASURKOVAM; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_JASURKOVAM TO ROLE ROLE_CZECHITA_JASURKOVAM; 
GRANT ALL ON SCHEMA SCH_CZECHITA_JASURKOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_JASURKOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_JASURKOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_JIMENEZL TO ROLE ROLE_CZECHITA_JIMENEZL; 
GRANT ROLE ROLE_CZECHITA_JIMENEZL TO USER CZECHITA_JIMENEZL; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_JIMENEZL TO ROLE ROLE_CZECHITA_JIMENEZL; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_JIMENEZL TO ROLE ROLE_CZECHITA_JIMENEZL; 
GRANT ALL ON SCHEMA SCH_CZECHITA_JIMENEZL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_JIMENEZL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_JIMENEZL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KALAFUTOVAN TO ROLE ROLE_CZECHITA_KALAFUTOVAN; 
GRANT ROLE ROLE_CZECHITA_KALAFUTOVAN TO USER CZECHITA_KALAFUTOVAN; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KALAFUTOVAN TO ROLE ROLE_CZECHITA_KALAFUTOVAN; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KALAFUTOVAN TO ROLE ROLE_CZECHITA_KALAFUTOVAN; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KALAFUTOVAN TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KALAFUTOVAN TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KALAFUTOVAN TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KOCOURKOVAE TO ROLE ROLE_CZECHITA_KOCOURKOVAE; 
GRANT ROLE ROLE_CZECHITA_KOCOURKOVAE TO USER CZECHITA_KOCOURKOVAE; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KOCOURKOVAE TO ROLE ROLE_CZECHITA_KOCOURKOVAE; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KOCOURKOVAE TO ROLE ROLE_CZECHITA_KOCOURKOVAE; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KOCOURKOVAE TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KOCOURKOVAE TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KOCOURKOVAE TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KOLAROVAM TO ROLE ROLE_CZECHITA_KOLAROVAM; 
GRANT ROLE ROLE_CZECHITA_KOLAROVAM TO USER CZECHITA_KOLAROVAM; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KOLAROVAM TO ROLE ROLE_CZECHITA_KOLAROVAM; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KOLAROVAM TO ROLE ROLE_CZECHITA_KOLAROVAM; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KOLAROVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KOLAROVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KOLAROVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KUNCOVAI TO ROLE ROLE_CZECHITA_KUNCOVAI; 
GRANT ROLE ROLE_CZECHITA_KUNCOVAI TO USER CZECHITA_KUNCOVAI; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KUNCOVAI TO ROLE ROLE_CZECHITA_KUNCOVAI; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KUNCOVAI TO ROLE ROLE_CZECHITA_KUNCOVAI; 
GRANT ALL ON SCHEMA SCH_CZECHITA_KUNCOVAI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_KUNCOVAI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_KUNCOVAI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MARKOVAP TO ROLE ROLE_CZECHITA_MARKOVAP; 
GRANT ROLE ROLE_CZECHITA_MARKOVAP TO USER CZECHITA_MARKOVAP; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MARKOVAP TO ROLE ROLE_CZECHITA_MARKOVAP; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MARKOVAP TO ROLE ROLE_CZECHITA_MARKOVAP; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MARKOVAP TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MARKOVAP TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MARKOVAP TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MORAVCOVAM TO ROLE ROLE_CZECHITA_MORAVCOVAM; 
GRANT ROLE ROLE_CZECHITA_MORAVCOVAM TO USER CZECHITA_MORAVCOVAM; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MORAVCOVAM TO ROLE ROLE_CZECHITA_MORAVCOVAM; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MORAVCOVAM TO ROLE ROLE_CZECHITA_MORAVCOVAM; 
GRANT ALL ON SCHEMA SCH_CZECHITA_MORAVCOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_MORAVCOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_MORAVCOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_NOVAKOVAK TO ROLE ROLE_CZECHITA_NOVAKOVAK; 
GRANT ROLE ROLE_CZECHITA_NOVAKOVAK TO USER CZECHITA_NOVAKOVAK; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_NOVAKOVAK TO ROLE ROLE_CZECHITA_NOVAKOVAK; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_NOVAKOVAK TO ROLE ROLE_CZECHITA_NOVAKOVAK; 
GRANT ALL ON SCHEMA SCH_CZECHITA_NOVAKOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_NOVAKOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_NOVAKOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_NOVOSILSKAO TO ROLE ROLE_CZECHITA_NOVOSILSKAO; 
GRANT ROLE ROLE_CZECHITA_NOVOSILSKAO TO USER CZECHITA_NOVOSILSKAO; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_NOVOSILSKAO TO ROLE ROLE_CZECHITA_NOVOSILSKAO; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_NOVOSILSKAO TO ROLE ROLE_CZECHITA_NOVOSILSKAO; 
GRANT ALL ON SCHEMA SCH_CZECHITA_NOVOSILSKAO TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_NOVOSILSKAO TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_NOVOSILSKAO TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_NUTELSY TO ROLE ROLE_CZECHITA_NUTELSY; 
GRANT ROLE ROLE_CZECHITA_NUTELSY TO USER CZECHITA_NUTELSY; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_NUTELSY TO ROLE ROLE_CZECHITA_NUTELSY; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_NUTELSY TO ROLE ROLE_CZECHITA_NUTELSY; 
GRANT ALL ON SCHEMA SCH_CZECHITA_NUTELSY TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_NUTELSY TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_NUTELSY TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PARASKEVAO TO ROLE ROLE_CZECHITA_PARASKEVAO; 
GRANT ROLE ROLE_CZECHITA_PARASKEVAO TO USER CZECHITA_PARASKEVAO; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PARASKEVAO TO ROLE ROLE_CZECHITA_PARASKEVAO; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PARASKEVAO TO ROLE ROLE_CZECHITA_PARASKEVAO; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PARASKEVAO TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PARASKEVAO TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PARASKEVAO TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PECHERSKAA TO ROLE ROLE_CZECHITA_PECHERSKAA; 
GRANT ROLE ROLE_CZECHITA_PECHERSKAA TO USER CZECHITA_PECHERSKAA; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PECHERSKAA TO ROLE ROLE_CZECHITA_PECHERSKAA; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PECHERSKAA TO ROLE ROLE_CZECHITA_PECHERSKAA; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PECHERSKAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PECHERSKAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PECHERSKAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PRUCHOVAK TO ROLE ROLE_CZECHITA_PRUCHOVAK; 
GRANT ROLE ROLE_CZECHITA_PRUCHOVAK TO USER CZECHITA_PRUCHOVAK; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PRUCHOVAK TO ROLE ROLE_CZECHITA_PRUCHOVAK; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PRUCHOVAK TO ROLE ROLE_CZECHITA_PRUCHOVAK; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PRUCHOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PRUCHOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PRUCHOVAK TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PUZMANOVAM TO ROLE ROLE_CZECHITA_PUZMANOVAM; 
GRANT ROLE ROLE_CZECHITA_PUZMANOVAM TO USER CZECHITA_PUZMANOVAM; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PUZMANOVAM TO ROLE ROLE_CZECHITA_PUZMANOVAM; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PUZMANOVAM TO ROLE ROLE_CZECHITA_PUZMANOVAM; 
GRANT ALL ON SCHEMA SCH_CZECHITA_PUZMANOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_PUZMANOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_PUZMANOVAM TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_REZLEROVAI TO ROLE ROLE_CZECHITA_REZLEROVAI; 
GRANT ROLE ROLE_CZECHITA_REZLEROVAI TO USER CZECHITA_REZLEROVAI; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_REZLEROVAI TO ROLE ROLE_CZECHITA_REZLEROVAI; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_REZLEROVAI TO ROLE ROLE_CZECHITA_REZLEROVAI; 
GRANT ALL ON SCHEMA SCH_CZECHITA_REZLEROVAI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_REZLEROVAI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_REZLEROVAI TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_RIZZIN TO ROLE ROLE_CZECHITA_RIZZIN; 
GRANT ROLE ROLE_CZECHITA_RIZZIN TO USER CZECHITA_RIZZIN; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_RIZZIN TO ROLE ROLE_CZECHITA_RIZZIN; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_RIZZIN TO ROLE ROLE_CZECHITA_RIZZIN; 
GRANT ALL ON SCHEMA SCH_CZECHITA_RIZZIN TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_RIZZIN TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_RIZZIN TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_RYBCHENKOL TO ROLE ROLE_CZECHITA_RYBCHENKOL; 
GRANT ROLE ROLE_CZECHITA_RYBCHENKOL TO USER CZECHITA_RYBCHENKOL; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_RYBCHENKOL TO ROLE ROLE_CZECHITA_RYBCHENKOL; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_RYBCHENKOL TO ROLE ROLE_CZECHITA_RYBCHENKOL; 
GRANT ALL ON SCHEMA SCH_CZECHITA_RYBCHENKOL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_RYBCHENKOL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_RYBCHENKOL TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SKALOVAG TO ROLE ROLE_CZECHITA_SKALOVAG; 
GRANT ROLE ROLE_CZECHITA_SKALOVAG TO USER CZECHITA_SKALOVAG; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SKALOVAG TO ROLE ROLE_CZECHITA_SKALOVAG; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SKALOVAG TO ROLE ROLE_CZECHITA_SKALOVAG; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SKALOVAG TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SKALOVAG TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SKALOVAG TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SESTAKOVAV TO ROLE ROLE_CZECHITA_SESTAKOVAV; 
GRANT ROLE ROLE_CZECHITA_SESTAKOVAV TO USER CZECHITA_SESTAKOVAV; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SESTAKOVAV TO ROLE ROLE_CZECHITA_SESTAKOVAV; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SESTAKOVAV TO ROLE ROLE_CZECHITA_SESTAKOVAV; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SESTAKOVAV TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SESTAKOVAV TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SESTAKOVAV TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SMIDOVAD TO ROLE ROLE_CZECHITA_SMIDOVAD; 
GRANT ROLE ROLE_CZECHITA_SMIDOVAD TO USER CZECHITA_SMIDOVAD; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SMIDOVAD TO ROLE ROLE_CZECHITA_SMIDOVAD; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SMIDOVAD TO ROLE ROLE_CZECHITA_SMIDOVAD; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SMIDOVAD TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SMIDOVAD TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SMIDOVAD TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SVECOVAV TO ROLE ROLE_CZECHITA_SVECOVAV; 
GRANT ROLE ROLE_CZECHITA_SVECOVAV TO USER CZECHITA_SVECOVAV; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SVECOVAV TO ROLE ROLE_CZECHITA_SVECOVAV; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SVECOVAV TO ROLE ROLE_CZECHITA_SVECOVAV; 
GRANT ALL ON SCHEMA SCH_CZECHITA_SVECOVAV TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_SVECOVAV TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_SVECOVAV TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_VITKOVAA TO ROLE ROLE_CZECHITA_VITKOVAA; 
GRANT ROLE ROLE_CZECHITA_VITKOVAA TO USER CZECHITA_VITKOVAA; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_VITKOVAA TO ROLE ROLE_CZECHITA_VITKOVAA; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_VITKOVAA TO ROLE ROLE_CZECHITA_VITKOVAA; 
GRANT ALL ON SCHEMA SCH_CZECHITA_VITKOVAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_VITKOVAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_VITKOVAA TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON SCHEMA SCH_CZECHITA_VOJACKOVAB TO ROLE ROLE_CZECHITA_VOJACKOVAB; 
GRANT ROLE ROLE_CZECHITA_VOJACKOVAB TO USER CZECHITA_VOJACKOVAB; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_VOJACKOVAB TO ROLE ROLE_CZECHITA_VOJACKOVAB; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_VOJACKOVAB TO ROLE ROLE_CZECHITA_VOJACKOVAB; 
GRANT ALL ON SCHEMA SCH_CZECHITA_VOJACKOVAB TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON FUTURE TABLES IN SCHEMA SCH_CZECHITA_VOJACKOVAB TO ROLE ROLE_CZECHITA_KOUC; 
GRANT ALL ON ALL TABLES IN SCHEMA SCH_CZECHITA_VOJACKOVAB TO ROLE ROLE_CZECHITA_KOUC; 
