-- Snowflake setup script: run as ACCOUNTADMIN once
-- Creates ROLE_PROVISIONER with minimal privileges and PROVISIONER user with RSA auth.

USE ROLE ACCOUNTADMIN;

-- Step 1: Create the provisioner role
CREATE ROLE IF NOT EXISTS ROLE_PROVISIONER;

-- Step 2: Grant minimal privileges to ROLE_PROVISIONER
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE ROLE_PROVISIONER;
GRANT CREATE USER ON ACCOUNT TO ROLE ROLE_PROVISIONER;
GRANT CREATE ROLE ON ACCOUNT TO ROLE ROLE_PROVISIONER;
GRANT CREATE SCHEMA ON DATABASE COURSES TO ROLE ROLE_PROVISIONER;
GRANT USAGE ON DATABASE COURSES TO ROLE ROLE_PROVISIONER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_PROVISIONER;

-- Step 3: Assign ROLE_PROVISIONER to SYSADMIN (so SYSADMIN can manage it)
GRANT ROLE ROLE_PROVISIONER TO ROLE SYSADMIN;

-- Step 4: Create PROVISIONER user
CREATE USER IF NOT EXISTS PROVISIONER
    DEFAULT_ROLE = ROLE_PROVISIONER
    DEFAULT_WAREHOUSE = COMPUTE_WH
    COMMENT = 'Czechitas provisioning service account';

-- Step 5: Set RSA public key for PROVISIONER (JWT auth -- no password)
ALTER USER PROVISIONER SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsuF3hse6tXEsUGuPFxSxtPe3UrA1eNnZKShkIrXVoo5cn+Z0OFcNbRWAwHCZc05E4NxGh7uXbrifVYNA5opIP11W0WyJkXcxNQQ5gECposYgsgDYOm9X6xLvRHGdCqTWMvUErtuNbEPpP71hezTNcJSj5WB72JWTRp5SBePcA9Fs1J9pFIMkiBLNqrdU+BDBzRk4K1Lc9WliIT3qL9kt7i2qgSdo43gyeeiWI5NPYm2hlR0jYWbwQCemsRanU8D+crvApWTaXO2KP0jcajV/NpGS461o3o88KvDInNAj2K8/YubPQejFYxa9SO/TX8xqrovmNtNp+pkyXIYU9FE+tQIDAQAB';

-- Step 6: Grant ROLE_PROVISIONER to PROVISIONER user
GRANT ROLE ROLE_PROVISIONER TO USER PROVISIONER;

-- Verification (run manually after setup):
-- SHOW GRANTS TO USER PROVISIONER;
-- SHOW GRANTS TO ROLE ROLE_PROVISIONER;
